<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<div class="content-block twitter-feed-block">
	<?php if($this->hasData('mgs_panel_title')): ?>
		<div class="content-heading">
			<h2 class="title"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></h2>
		</div>
	<?php endif ?>
	
	<?php if($this->hasData('mgs_panel_note')): ?>
		<div class="block-note"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_note')) ?></div>
	<?php endif ?>

	<div class="block-content">
		<?php echo $this->getLastTwitter($this->getFeedCount(), $this->getTruncate()); ?>
	</div>
</div>