<?php

/**

 * Copyright © 2015 Magento. All rights reserved.

 * See COPYING.txt for license details.

 */



// @codingStandardsIgnoreFile



/** @var $block \Magento\Catalog\Block\Product\View */

?>

<?php $_product = $block->getProduct(); ?>

<?php $buttonTitle = __('Add to Cart'); ?>
<?php 
$_akeansHelper = $this->helper('Akeans\ShowPriceAfterLogin\Helper\Data');
$akeans_check = $_akeansHelper->checkVisible($_product);
?>
<?php if ($_product->isSaleable()): ?>

<div class="box-tocart">

    <div class="fieldset">
        <?php if(!$_akeansHelper->isCustomerlogin() && $_akeansHelper->isEnableShowPriceAfterLogin() && $akeans_check): 
            $redirect_url = $_akeansHelper->getRedirectUrl();
            if($redirect_url){
            ?>
        <a  class="price-msg" href="<?php echo $block->getUrl($redirect_url); ?>">
                    <?php  echo $_akeansHelper->getButtonTitle();?>
                </a>
            <?php }else{?>
                <a  class="price-msg" href="<?php echo $block->getUrl('customer/account/login'); ?>">
                    <?php  echo $_akeansHelper->getButtonTitle();?>
                </a>
            <?php }?>
            <?php elseif($_akeansHelper->isCustomerlogin() && $_akeansHelper->isEnableShowPriceAfterLogin() && !$akeans_check):?>	
            <?php $redirect_url = $_akeansHelper->getRedirectUrl();
            if($redirect_url){
            ?>
                <a  class="price-msg" href="<?php echo $block->getUrl($redirect_url); ?>">
                    <?php  echo $_akeansHelper->getCallPriceLabel();?>
                </a>
            <?php }else{?>
                <a  class="price-msg" href="<?php echo $block->getUrl('customer/account/login'); ?>">
                    <?php  echo $_akeansHelper->getCallPriceLabel();?>
                </a>
            <?php }?>
            <?php else:?>
        
        <?php if ($block->shouldRenderQuantity()): ?>

        <div class="field qty">

            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Quantity :') ?></span></label>

            <div class="control">

                <input type="number"

                       name="qty"

                       id="qty"

                       maxlength="12"

                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"

                       title="<?php /* @escapeNotVerified */ echo __('Quantity') ?>" class="input-text qty"

                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"

                       />

            </div>

        </div>

        <?php endif; ?>

        <div class="actions">

            <button type="submit"

                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"

                    class="action primary tocart"

                    id="product-addtocart-button">

                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>

            </button>

            <?php echo $block->getChildHtml('', true) ?>

        </div>
        <?php endif; ?>
    </div>

</div>

<?php endif; ?>

<?php if ($block->isRedirectToCartEnabled()) : ?>

<script type="text/x-magento-init">

    {

        "#product_addtocart_form": {

            "Magento_Catalog/product/view/validation": {

                "radioCheckboxClosest": ".nested"

            }

        }

    }

</script>

<?php else : ?>

<script>

    require([

        'jquery',

        'mage/mage',

        'Magento_Catalog/product/view/validation',

        'Magento_Catalog/js/catalog-add-to-cart'

    ], function ($) {

        'use strict';



        $('#product_addtocart_form').mage('validation', {

            radioCheckboxClosest: '.nested',

            submitHandler: function (form) {

                var widget = $(form).catalogAddToCart({

                    bindSubmit: false

                });



                widget.catalogAddToCart('submitForm', $(form));



                return false;

            }

        });

    });

</script>

<?php endif; ?>