<?php $images = $this->getImages() ?>
<?php if(count($images)>0): ?>
	<?php $links = $this->getLinks() ?>
	<?php $blockId = rand() . time(); ?>
	<?php $animated = $this->getAnimateSlider(); ?>
	<div id="mgs-slider-<?php echo $blockId ?>" class="slider_mgs_carousel owl-carousel">
		<?php foreach($images as $key=>$image): ?>
			<?php if(isset($links[$key]) && ($links[$key]!='')): ?>
				<a href="<?php echo $links[$key] ?>">
					<img src="<?php echo $image ?>" alt=""/>
				</a>
			<?php else: ?>
				<img src="<?php echo $image ?>" alt=""/>
			<?php endif ?>
			
		<?php endforeach ?>
	</div>
	<script type="text/javascript">
		require([
			'jquery',
			'mgs/owlcarousel'
		], function(jQuery){
			(function($) {
				$("#mgs-slider-<?php echo $blockId ?>").owlCarousel({
					items: 1,
					rtl: <?php echo $this->getRightToLeft(); ?>,
					loop: <?php echo $this->getLoop(); ?>,
					nav: <?php echo $this->getControlNav(); ?>,
					dots: <?php echo $this->getControlDots(); ?>,
					autoplayTimeout: <?php echo $this->getAutoSpeed(); ?>,
					autoplay: <?php echo $this->getAutoPlay(); ?>,
					autoplayHoverPause: <?php echo $this->getStopAuto() ? 'true' : 'false'; ?>,
					animateOut: '<?php echo $animated['out'] ?>',
					animateIn: '<?php echo $animated['in'] ?>',
					navText: ["<i class='fa fa-arrow-left'></i>","<i class='fa fa-arrow-right'></i>"]
				});
			})(jQuery);
		});
	</script>
<?php else: ?>
	<div role="alert" class="alert alert-warning"><?php echo __('There are no sliders matching the selection.') ?></div>
<?php endif ?>