<?php

/**

 * Copyright © 2015 RokanThemes.com. All rights reserved.



 * @author RokanThemes Team <contact@rokanthemes.com>

 */

?>

<?php

/**

 * Blog sidebar recent posts template

 *

 * @var $block \Rokanthemes\Blog\Block\Sidebar\Recent

 */

?>



<?php

	// $enable = $this->getConfig('enable_frontend');

	// $auto = $this->getConfig('auto');

	// $speed = $this->getConfig('speed');

	 $default = 2;//$this->getConfig('default');

	 $desktop = 2;//$this->getConfig('desktop');

	// $desktop_small = $this->getConfig('desktop_small');

	// $tablet = $this->getConfig('tablet');

	// $mobile = $this->getConfig('mobile');

	// $pagination = $this->getConfig('pagination');

	// $show_next_back = $this->getConfig('show_next_back');

	// $show_navigation_control = $this->getConfig('show_navigation_control');

	   $title = 'From Our Blog';//$this->getConfig('title');

	// if($show_next_back)

	// 	$show_next_back = 'true';

	// else

	// 	$show_next_back = 'false';

	// $show_navigation_control = $this->getConfig('show_navigation_control');

	// if($show_navigation_control)

	// 	$show_navigation_control = 'true';

	// else

	// 	$show_navigation_control = 'false';

	$_postCollection = $block->getPostCollection();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$mediaUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')

                    ->getStore()

                    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

?>

<?php if ($_postCollection->count()) { ?>

<section class="widget box-section block-recent-posts" data-bind="scope: 'recemt-posts'">

	<div class="container"> 

		<div class="rokan-product-heading rokan-onsale-heading">

			<h2><?php echo __($title) ?></h2>

		</div>

		<div class="owl-container">

			<div class="block-content">

				<div class="owl">

					<?php foreach ($_postCollection as $_post) { ?>

					

						<div class="item">

							<div class="product-item">

								<div class="post-thumb">

									<a href="<?php echo $_post->getPostUrl() ?>">

										<img src="<?php echo $mediaUrl.$_post->getFeaturedImg() ?>"/>

									</a>

									

								</div>

								<div class="blog-content">
                                    <div class="post-info">
									<div class="post-date">

										<?php 

											$date = $_post->getPublishTime();

										?>

										<span class="day"><span class="date"><?php echo __(date("d", strtotime($date))) ?></span><span class="month">/ <?php echo __(date("M", strtotime($date))) ?></span></span>

									</div>
                                    <div class="post-title"><a href="<?php echo $_post->getPostUrl() ?>"><?php echo $block->escapeHtml($_post->getTitle()) ?></a></div>    
									<div class="blog-content-inner">

										<div class="short-des"><?php echo substr($_post->getContent(),0,200).'...' ?></div>

										<a class="readmore" href="<?php echo $_post->getPostUrl() ?>">
                                            <span class="readmore-text"><?php echo __('Read more') ?></span>
											<span class="fa fa-angle-double-right"></span>
										</a>

									</div>
                                    </div>
								</div>

							</div>

						</div>

					<?php } ?>

				</div>

			</div>

		</div>

    </div>

</section>



<script type="text/javascript">

	 require([

	 	'jquery',

	 	'mage/mage',

	 	'rokanthemes/owl'

	 ], function ($) {

	 	'use strict';



	 	jQuery(".block-recent-posts .owl").owlCarousel({

	 		items : 2,

			itemsDesktop : [1199,2],

			itemsDesktopSmall : [980,1],

			itemsTablet: [768,1],

			itemsMobile : [479,1],

			slideSpeed : 500,

			paginationSpeed : 500,

			rewindSpeed : 500,

			addClassActive: true,

			navigation : true,

			stopOnHover : true,

			pagination : false,

			scrollPerPage:true,

	 	});

	 });

</script>

<?php } ?>