<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Perm
 */
?>
<script>
    require([
        'jquery',
        'mage/adminhtml/grid',
        "Magento_Variable/variables",
        'prototype'
    ], function(jQuery){
        <!--
        <?php $myBlock = $block->getLayout()->getBlock('dealerCustomersGrid'); ?>
        <?php if (is_object($myBlock) && $myBlock->getJsObjectName()): ?>
        var checkBoxes = $H(<?php /* @escapeNotVerified */ echo $myBlock->getCustomers(true) ?>);
        var warning = false;
        if (checkBoxes.size() > 0) {
            warning = true;
        }
        jQuery('#in_dealer_customer').val(checkBoxes.toQueryString());

        function registerCustomerDealer(grid, element, checked)
        {
            if (checked) {
                checkBoxes.set(element.value, 0);
            } else {
                checkBoxes.unset(element.value);
            }
            $('in_dealer_customer').value = checkBoxes.toQueryString();
            grid.reloadParams = {'in_dealer_customer[]':checkBoxes.keys()};
        }

        function dealerCustomersRowClick(grid, event)
        {
            var trElement = Event.findElement(event, 'tr');
            var isInput   = Event.element(event).tagName == 'INPUT';
            if (trElement) {
                var checkbox = Element.getElementsBySelector(trElement, 'input');
                if(checkbox[0]){
                    var checked = isInput ? !checkbox[0].checked : checkbox[0].checked;
                    if (checked) {
                        if ( true || confirm("<?php /* @escapeNotVerified */ echo __('Warning!\r\nThis action will remove this customer from already assigned dealer\r\nAre you sure?') ?>") ) {
                            checkbox[0].checked = false;
                            checkBoxes.unset(checkbox[0].value);
                            varienElementMethods.setHasChanges(checkbox[0]);
                        } else {
                            checkbox[0].checked = true;
                        }
                    } else {
                        checkbox[0].checked = true;
                        checkBoxes.set(checkbox[0].value, true);
                    }

                    $('in_dealer_customer').value = checkBoxes.toQueryString();
                    grid.reloadParams = {'in_dealer_customer[]':checkBoxes.keys()};
                }
            }
        }

        function dealerCustomersRowInit(grid, row)
        {
            var checkbox = $(row).getElementsByClassName('checkbox')[0];
            if (checkbox) {
                if (checkbox.checked) {
                    checkBoxes.set(checkbox.value, checkbox.checked);
                } else {
                    checkBoxes.unset(checkbox.value);
                }

                $('in_dealer_customer').value = checkBoxes.toQueryString();
                grid.reloadParams = {'in_dealer_customer[]':checkBoxes.keys()};
            }
        }

        function massSelectCustomers(allCheckbox)
        {
            <?php /* @escapeNotVerified */ echo $myBlock->getJsObjectName() ?>.rows.each(function(row)
        {
            $(row).getElementsByClassName('checkbox')[0].checked = allCheckbox.checked;
            dealerCustomersRowInit(<?php /* @escapeNotVerified */ echo $myBlock->getJsObjectName() ?>, row);
        });
        }
        Event.observe(window, "load", function(){
            <?php /* @escapeNotVerified */ echo $myBlock->getJsObjectName() ?>.rowClickCallback = dealerCustomersRowClick;
            <?php /* @escapeNotVerified */ echo $myBlock->getJsObjectName() ?>.initRowCallback = dealerCustomersRowInit;
            <?php /* @escapeNotVerified */ echo $myBlock->getJsObjectName() ?>.checkboxCheckCallback = registerCustomerDealer;
            <?php /* @escapeNotVerified */ echo $myBlock->getJsObjectName() ?>.checkCheckboxes = massSelectCustomers;
            <?php /* @escapeNotVerified */ echo $myBlock->getJsObjectName() ?>.rows.each(function(row){dealerCustomersRowInit(<?php /* @escapeNotVerified */ echo $myBlock->getJsObjectName() ?>, row)});
            $('in_dealer_customer_old').value = $('in_dealer_customer').value;
        });
        <?php endif; ?>
//-->

    });
</script>
