<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block discount boxed-checkout" id="block-discount" data-mage-init='{"collapsible":{"openedState": "active", "saveState": false, "active": true}}'>
	<div class="block-title" data-role="title">
		<h3 class="title" aria-level="2" role="heading" id="block-discount-heading"><span><?php /* @escapeNotVerified */ echo __('Apply Discount Code') ?></span></h3>
	</div>
    <div class="content" data-role="content" aria-labelledby="block-discount-heading">
        <form id="discount-coupon-form"
              action="<?php /* @escapeNotVerified */ echo $block->getUrl('checkout/cart/couponPost') ?>"
              method="post"
              data-mage-init='{"discountCode":{"couponCodeSelector": "#coupon_code",
                                               "removeCouponSelector": "#remove-coupon",
                                               "applyButton": "button.action.apply",
                                               "cancelButton": "button.action.cancel"}}'>
            <div class="fieldset coupon<?php strlen($block->getCouponCode()) ? ' applied' : ''?>">
                <input type="hidden" name="remove" id="remove-coupon" value="0" />
                <div class="form-group">
                       <div class="control">
                        <input type="text" class="input-text" id="coupon_code" name="coupon_code" value="<?php echo $block->escapeHtml($block->getCouponCode()) ?>" placeholder="<?php echo $block->escapeHtml(__('Enter your coupon code'));?>" />
                    
                        <div class="actions-toolbar">
                            <?php if (!strlen($block->getCouponCode())): ?>
                            <div class="primary">
                                <button class="action apply btn" type="button" value="<?php /* @escapeNotVerified */ echo __('Apply Code') ?>">
                                    <span><?php /* @escapeNotVerified */ echo __('Apply Code') ?></span>
                                </button>
                            </div>
                            <?php else: ?>
                                <div class="primary">
                                    <button  type="button" class="action cancel btn" value="<?php /* @escapeNotVerified */ echo __('Cancel Coupon') ?>"><span><?php /* @escapeNotVerified */ echo __('Cancel Coupon') ?></span></button>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    
                </div>
                
            </div>
        </form>
    </div>
</div>
