<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>

<div data-block="minicart" class="minicart-wrapper block-cart-header switcher ">
    <a class="action showcart" href="<?php echo $block->getShoppingCartUrl(); ?>"
       data-bind="scope: 'minicart_content'">
		<div class="box-shopbag">
			<div class="icon-cart">
				<span class="ion-ios-cart-outline"></span>
				<span data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading" class="count qty">
					<span class="counter-number loaded"><!-- ko text: getCartParam('summary_count') -->0<!-- /ko --></span>
					<span class="counter-number firstload">0</span>
				</span>			
			</div>
			<div class="title-cart">
				<span class="text"><?php echo __('My cart')?></span>
				<!-- ko if: getCartParam('subtotal') -->
					<span data-bind="html: getCartParam('subtotal')"></span>
				<!-- /ko -->
			</div>
		</div>		
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart empty" style="display:none;"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "defaultDialogClass":"dropdown-menu",
                "buttons":null}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
			<?php echo $block->getChildHtml('minicart.addons'); ?>
        </div>
    <?php endif ?>
    <script>
        window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        },
		"*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
</div>

