<?php $_testimonialCollection = $this->getCollection(); ?>
<?php $_collectionSize = count($_testimonialCollection) ?>
<?php $helper = $this->helper('MGS\Testimonial\Helper\Data'); ?>

<div class="content-block testimonial-block testimonial-list-block">
	<?php if($this->hasData('mgs_panel_title')): ?>
		<div class="content-heading">
			<h2 class="title"><?php echo $helper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></h2>
		</div>
	<?php endif ?>

	<?php if (count($_testimonialCollection) >0): ?>
		<?php if($this->hasData('mgs_panel_note')): ?>
			<div class="block-note"><?php echo $helper->decodeHtmlTag($this->getData('mgs_panel_note')) ?></div>
		<?php endif ?>
		
		<?php
			$blockId = rand() . time();
			$useSlider = $this->getUseSlider();
			$showAvatar = $this->getShowAvatar();
			$perRow = $this->getPerrow();
		?>
		<?php if ($useSlider): ?>
			<div class="block widget mgs-testimonial">
				<div class="owl-carousel testimonial-grid mgs-carousel-<?php echo $blockId; ?>">
					<?php foreach ($_testimonialCollection as $testimonial): ?>
						<div class="item testimonial-author">
							<?php if($showAvatar && $this->getAvatarUrl($testimonial->getAvatar())): ?>
								<div class="img-thumbnail img-thumbnail-small">							
									<img src="<?php echo $this->getAvatarUrl($testimonial->getAvatar()) ?>" alt="">							
								</div>
							<?php endif;?>
							<div class="testimonial-content">
								<p><?php echo $testimonial->getContent() ?></p>
							</div>
							<p><span><?php echo __('from') ?></span><strong><?php echo $testimonial->getName() ?></strong></p>
						</div>
					<?php endforeach ?>
				</div>
			</div>
			<script type="text/javascript">
				require([
					'jquery',
					'mgs/owlcarousel'
				], function ($) {
					var owl<?php echo $blockId ?> = $('.mgs-carousel-<?php echo $blockId ?>').owlCarousel({
						items: <?php echo $perRow; ?>,
						autoplay: <?php echo $this->getAutoplay() ? 'true' : 'false' ?>,
						autoplayHoverPause: <?php echo $this->getStopAuto() ? 'true' : 'false' ?>,
						nav: <?php echo $this->getNavigation() ? 'true' : 'false' ?>,
						dots: <?php echo $this->getPagination() ? 'true' : 'false' ?>,
						margin:30,
						responsive:{
							0:{
								items:1,
								margin:0
							},
							480:{
								items:2,
								margin:20
							},
							768:{
								items:<?php echo $perRow; ?>
							}
						}
					});
					<?php if($this->getPagination()): ?>
						owl<?php echo $blockId ?>.on('changed.owl.carousel', function (event) {
							if (event.item.count - event.page.size == event.item.index)
								$(event.target).find('.owl-dots div:last')
								  .addClass('active').siblings().removeClass('active');
						});
					<?php endif ?>
				});
			</script>
		<?php else: ?>
			<div class="block widget mgs-testimonial">
				<div class="block-content">
					<?php $col = $helper->convertPerRowtoCol($perRow); ?>
					<ul class="row <?php echo $helper->convertColClass($col, 'row') ?>">
						<?php foreach ($_testimonialCollection as $testimonial): ?>
							<li class="item testimonial-author">
								<?php if($showAvatar && $this->getAvatarUrl($testimonial->getAvatar())): ?>
									<div class="img-thumbnail img-thumbnail-small">							
										<img src="<?php echo $this->getAvatarUrl($testimonial->getAvatar()) ?>" alt="">							
									</div>
								<?php endif;?>
								<div class="testimonial-content">
									<p><?php echo $testimonial->getContent() ?></p>
								</div>
								<p><span><?php echo __('from') ?></span><strong><?php echo $testimonial->getName() ?></strong></p>
							</li>
						<?php endforeach ?>
					</ul>
				</div>
			</div>
		<?php endif ?>
	<?php else: ?>
		<div role="alert" class="alert alert-warning"> <?php echo __('There are no testimonials matching the selection.') ?> </div>
	<?php endif ?>
</div>