<?php

$scopeId = $block->getScopeId();
$scope = $block->getScope();
$defaultLabel = __('Use Default');
$defaultTitle = __('-- Please Select --');
$scopeLabel = __('STORE VIEW');
?>
<?php $path = "mwquickorder/style_management/style";?>
<?php $data = $block->getFieldEnableBackEnd($path, $scope, $scopeId); ?>
<?php $active = ($scope == 'default' || !empty($data)); ?>
<?php $style = $block->getDefaultField($path, $scope, $scopeId);?>
<?php
$customPath = 'mwquickorder/style_management/custom_style';
$custom = $this->getDefaultField($customPath, $scope, $scopeId);
?>
<div class="color-title"><?php echo  __('Quick Order Buttons Color');?></div>
<table>
    <tr>
<td class="value">
    <select data-current-value="" style="width: 280px;margin-left:30px;"
            id="<?php echo $block->getElementHtmlId('style') ?>"
            name="<?php echo $block->getElementHtmlName('style') ?>"
        <?php echo $active ? '' : 'disabled=""' ?>
            class="select"
        >
        <?php foreach ($block->getFieldOptions() as $value => $label): ?>
            <?php $selected = $data ? $data : $block->getDefaultField($path, $scope, $scopeId); ?>
            <option
                value="<?php echo $value ?>" <?php echo ($selected == $value) ? 'selected="selected"' : '' ?>>
                <?php echo $label ?>
            </option>
        <?php endforeach; ?>
    </select>
    <label for="<?php echo $block->getElementHtmlId('style') ?>"></label>
</td>
<?php if ($scope != 'default'): ?>
    <td class="use-default">
        <input type="checkbox" value="1" class="checkbox config-inherit"
               id="<?php echo $block->getCheckBoxElementHtmlId('style') ?>"
               name="<?php echo $block->getCheckBoxElementHtmlName('style') ?>"
            <?php echo $data ? '' : 'checked="checked"' ?>
               onclick="toggleValueElements(this, Element.previous(this.parentNode))"
            />
        <label for="<?php echo $block->getCheckBoxElementHtmlId('style') ?>"
               class="inherit"
               title="<?php echo $defaultTitle ?>">
            <?php echo $defaultLabel ?>
        </label>
    </td>

<td class="scope-label">[<?php echo $scopeLabel ?>]</td>

<?php endif;?>
</tr></table>
<?php if ($style=='custom') :?>
   <div id="showreview"></div>
   <div id="style-color">
       <label for="mwquickorder_style_management_custom"></label>
        <input value="<?php echo $custom;?>"
               style="background-color: <?php echo $custom?>"
               name=groups[style_management][fields][custom_style][value]
               class="jscolor custom-color"
               id="mwquickorder_style_management_custom" />
    </div>
<?php else :?>
    <div id="showreview">
        <img width="957px" src="<?php echo $block->getImageColor($style);?>" />
    </div>
     <div id="style-color" style="display: none">
         <label for="mwquickorder_style_management_custom"></label>
        <input value="" name="groups[style_management][fields][custom_style][value]"
               class="jscolor custom-color"
               id="mwquickorder_style_management_custom" />
    </div>
<?php endif;?>
<style type="text/css">
    .custom-color {
        margin-left: 30px;
        margin-top:10px;
    }
    .color-title {
        margin-top: 10px;
        font-weight: bold;
        border-bottom: 1px solid rgb(223, 223, 223);
    }
    #quickorder_style_management_style, #quickorder_style_management_button {
        width: 280px;
        margin-left:30px;
    }
</style>
<script type="text/javascript">
    require(["Magewares_MWQuickOrder/js/jscolor.min"],function($){});
    require(["jquery"],function($){
        var styleObject = $("#mwquickorder_style_management_style");
        var styleButtonObject = $("#mwquickorder_style_management_button");
        var showReview = $("#showreview");
        styleObject.change(function(){
            var optionSelect = styleObject.find("option:selected");
            var optionSelectValue = optionSelect.val();
            if (optionSelectValue=="custom") {
                showReview.hide();
                $("#style-color").show();
            } else {
                var show = "<img width=\"957px\" src=\"<?php echo $this->getViewFileUrl('Magewares_MWQuickOrder::images/style'); ?>";
                show +="/"+optionSelectValue+".png\" />";
                showReview.html(show);
                showReview.show();
                $("#style-color").hide();
            }
        });
        styleButtonObject.change(function(){
            var optionSelect = styleButtonObject.find("option:selected");
            var optionSelectValue = optionSelect.val();
            if (optionSelectValue == "custom") {
                $("#edit-button-color").show();
            } else {
                $("#edit-button-color").hide();
            }
        });
    });
</script>