<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
$mpanelHelper = $this->helper('MGS\Mpanel\Helper\Data');
?>

<div class="block block-search" id="trigger-search">
    <div class="block block-content">		
		<a class="btn btn-open-search action toggle search-trigger" id="open-search"><span class="ion-ios-search-strong"></span></a>
		<?php if($mpanelHelper->getStoreConfig('mgstheme/general/header') != 'header_1' && $mpanelHelper->getStoreConfig('mgstheme/general/header') != 'header_5' && $mpanelHelper->getStoreConfig('mgstheme/general/header') != 'header_6' ): ?>
			<div class="dropdown search-dropdown" style="display: none" data-mage-init='{"dropdownDialog":{
											 "appendTo":"#trigger-search",
											 "triggerTarget":"#open-search",
											 "closeOnMouseLeave":false,
											 "triggerClass":"active",
											 "parentClass":"active",
											 "buttons":null,
											 "defaultDialogClass":"dropdown-menu"}}'>

		<?php endif;?>
        <form class="form minisearch form-inline" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">			
			<div class="form-search">
				<?php if($mpanelHelper->getStoreConfig('mpanel/form_mini_search/show_categories')): ?>
				<?php $categories = $mpanelHelper->getCategories(); ?>
				<?php $currentCategory = ""; ?>
				<?php $currentCategoryId = ""; ?>
				<?php foreach ($categories as $category) {
						foreach ($category as $key => $value) {
							if ($key == 'label') { $categoryName = $value; }
							if ($key == 'value') { $categoryId = $value; }
						}
						if ($mpanelHelper->getCurrentlySelectedCategoryId() == $categoryId){
							$currentCategory = $categoryName;
							$currentCategoryId = $categoryId;
							break;
						}
					} ?>
					<input type="hidden" name="cat" id="cat" value="<?php echo $currentCategoryId; ?>"/>
					<div class="search-select <?php if($mpanelHelper->getStoreConfig('mgstheme/general/header') == 'header_1'): ?> no-display <?php endif;?>">
						<a href="#" id="toggleCatSearch">
							<span id="cat-active-name" class="search-cat-active">
								<?php if($currentCategory != ""): ?>
									<?php echo $currentCategory ?>
								<?php else: ?>
									<?php echo __('All Categories'); ?>
								<?php endif ?>
							</span>
							<span class="pull-right"><span class="fa fa-angle-down"></span></span>
						</a>
						<ul id="select-cat-dropdown" style="display:none;">
							<li class="parent">
								<span onclick="setSearchCatValue('', '<?php echo __('All Categories') ?>');"><?php echo __('All Categories') ?></span>
							</li>
							<?php
								foreach ($categories as $category) {
									foreach ($category as $key => $value) {
										if ($key == 'label') {
											$categoryName = $value;
										}
										if ($key == 'value') {
											$categoryId = $value;
										}
										if ($key == 'level') {
											$categoryLevel = $value;
										}
									}
									?>
									<li <?php if($categoryLevel >= 3): ?>style="padding-left: 10px;"<?php endif ?> class="<?php if($categoryLevel < 3): ?>parent<?php endif ?> level<?php echo $categoryLevel ?> <?php if ($mpanelHelper->getCurrentlySelectedCategoryId() == $categoryId): ?>active<?php endif; ?>">
										<span onclick="setSearchCatValue('<?php echo $categoryId; ?>', '<?php echo $categoryName; ?>');"><?php echo $categoryName; ?></span>
									</li>
									<?php
								}
							?>
						</ul>
					</div>
				<?php endif; ?>
				<input id="search"
				   data-mage-init='{"quickSearch":{
						"formSelector":"#search_mini_form",
						"url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest'); ?>",
						"destinationSelector":"#search_autocomplete"}
				   }'
				   type="text"
				   name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"			  
				   placeholder="<?php echo __('Search'); ?>"			   
				   value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
				   class="input-text form-control"
				   maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
				   role="combobox"
				   aria-expanded="true"
				   aria-haspopup="false"
				   aria-autocomplete="both"
				   autocomplete="off"/>
					
				<button type="submit" title="<?php echo $block->escapeHtml(__('Search')) ?>" class="button btn btn-primary">
					<i class="ion-ios-search-strong"></i>
				</button>	   
				<div id="search_autocomplete" class="search-autocomplete" style="display: none;"></div>
				<?php echo $block->getChildHtml() ?>
			</div>
        </form>
		<?php if($mpanelHelper->getStoreConfig('mgstheme/general/header') != 'header_1' && $mpanelHelper->getStoreConfig('mgstheme/general/header') != 'header_5' && $mpanelHelper->getStoreConfig('mgstheme/general/header') != 'header_6' ): ?>
			</div>
		<?php endif;?>
    </div>
</div>
<?php if($mpanelHelper->getStoreConfig('mpanel/form_mini_search/show_categories')): ?>
<script type="text/javascript">
		require([
			'jquery'
			], function(jQuery){
				(function($) {
					$(document).ready(function(){						
						$('#toggleCatSearch').click(function(e){
							e.preventDefault();
							$('#select-cat-dropdown').slideToggle();
							$('.search-select > a').toggleClass('open');
						});
					});
				})(jQuery);
			});
			function setSearchCatValue(id,name){
				require([
				'jquery'
				], function(jQuery){
					(function($) {
						$('#cat').val(id);
						$('#cat-active-name').html(name);
						$('#select-cat-dropdown').hide();
						$('.search-select > a').removeClass('open');
					})(jQuery);
				});
			}
		</script>
<?php endif;?>