<?php
$helper = $this->helper('MGS\Blog\Helper\Data');
$collection = $block->getPostCollection();
?>

<div class="content-block blog-block blog-grid-list-block">
    <?php if ($this->getData('mgs_panel_title')): ?>
        <div class="title-block">
            <h2><?php echo $helper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></h2>
            <?php if ($this->getData('mgs_panel_note')): ?>
                <div class="block-note"><?php echo $helper->decodeHtmlTag($this->getData('mgs_panel_note')) ?></div>
            <?php endif ?>
        </div>
    <?php endif ?>

    <?php if (count($collection)): ?>

       

        <?php
        $blockId = rand() . time();
        $showShortContent = $this->getConfig('show_short_content');
        $viewAs = $this->getConfig('view_as');
        $showThumbnail = $this->getConfig('show_thumbnail');
        ?>

        <?php if ($viewAs == 'owl_carousel'): ?>
            <div class="block widget mgs-blog-lastest-posts">
                <div class="block-content">
                    <div class="owl-carousel mgs-carousel-<?php echo $blockId; ?>">
                        <?php foreach ($collection as $post): ?>
                            <div class="item">
                                <?php if ($showThumbnail): ?>
                                    <?php if ($post->getThumbType() == "video"): ?>
                                            <?php if ($helper->getThumbnailImgVideoPost($post) != ""): ?>
                                                <div class="video image" data-toggle="modal" data-target="#postModal-sidebar--<?php echo $post->getId() ?>">
                                                    <img class="img-responsive" src="<?php echo $helper->getThumbnailImgVideoPost($post); ?>" />
                                                </div>
                                            <?php endif ?>
                                        <?php else: ?>
                                            <div class="image"><?php echo $helper->getThumbnailPost($post); ?></div>
                                        <?php endif ?>
                                <?php endif ?>
                                <h4 class="title"><a href="<?php echo $post->getPostUrlWithNoCategory(); ?>" title="<?php echo $post->getTitle(); ?>"><?php echo $post->getTitle() ?></a></h4>
                                <?php if ($showShortContent): ?>
                                    <div class="short-content">
                                        <?php echo substr($post->getShortContent(), 0, $this->getConfig('limit_characters_short_content')); ?>
                                    </div>
                                <?php endif ?>
                                <div class="read-more">
                                    <a href="<?php echo $post->getPostUrlWithNoCategory(); ?>"><?php echo __e('Read more') ?></a>
                                </div>
                            </div>
                        <?php endforeach ?>
                    </div>
                </div>
            </div>

            <script type="text/javascript">
                require([
                    'jquery',
                    'mgs/owlcarousel'
                ], function ($) {
                    var owl<?php echo $blockId ?> = $('.mgs-carousel-<?php echo $blockId ?>').owlCarousel({
                        items: <?php echo $this->getConfig('items', 5); ?>,
                        autoplay: <?php echo $this->getConfig('autoplay') ? 'true' : 'false' ?>,
                        autoplayHoverPause: <?php echo $this->getConfig('stop_auto') ? 'true' : 'false' ?>,
                        nav: <?php echo $this->getConfig('navigation') ? 'true' : 'false' ?>,
                         navText: ['<span class="ion-ios-arrow-left"></span>', '<span class="ion-ios-arrow-right"></span>'],
                        dots: <?php echo $this->getConfig('pagination') ? 'true' : 'false' ?>,
                        margin: 30,
                        responsive: {
                            0: {
                                items: 1,
                                margin: 0
                            },
                            480: {
                                items: 2,
                                margin: 20
                            },
                            768: {
                                items:<?php echo $this->getConfig('items', 5); ?>
                            }
                        }
                    });
        <?php if ($this->getConfig('pagination')): ?>
                        owl<?php echo $blockId ?>.on('changed.owl.carousel', function (event) {
                            if (event.item.count - event.page.size == event.item.index)
                                $(event.target).find('.owl-dots div:last')
                                        .addClass('active').siblings().removeClass('active');
                        });
        <?php endif ?>
                });
            </script>
        <?php else: ?>
            <div class="block widget mgs-blog-lastest-posts">

                <div class="block-content row">
                    <?php $perRow = $this->getConfig('items', 5); ?>
                    <?php $col = $helper->convertPerRowtoCol($perRow); ?>                    
                    <div class="col-md-6">
                        <?php
                        $j = 0;
                        foreach ($collection as $post):
                            ?> 
                            <?php if ($j > 0): ?>
                                <?php break; ?>
                                <?php endif; ?>
                            <div class="item-first">
                                    <?php if ($showThumbnail): ?>
                                    <div class="post-top">
                                        <?php if ($post->getThumbType() == "video"): ?>
                                            <?php if ($helper->getThumbnailImgVideoPost($post) != ""): ?>
                                                <div class="video image" data-toggle="modal" data-target="#postModal-sidebar--<?php echo $post->getId() ?>">
                                                    <img class="img-responsive" src="<?php echo $helper->getThumbnailImgVideoPost($post); ?>" />
                                                </div>
                                            <?php endif ?>
                                        <?php else: ?>
                                            <div class="image"><?php echo $helper->getThumbnailPost($post); ?></div>
                                        <?php endif ?>
                                    </div>
            <?php endif ?>
                                <div class="post-bottom">
                                    <div class="post-meta">
                                        <p class="h6"><?php echo __('%1', $block->formatDate($post->getCreatedAt(), \IntlDateFormatter::FULL, false)); ?></p>
                                    </div>
                                    <h4 class="title"><a href="<?php echo $post->getPostUrlWithNoCategory(); ?>" title="<?php echo $post->getTitle(); ?>"><?php echo $post->getTitle() ?></a></h4>
                                        <?php if ($showShortContent): ?>
                                        <div class="short-content">
                <?php echo substr($post->getShortContent(), 0, $this->getConfig('limit_characters_short_content')); ?>
                                        </div>
                                        <div class="read-more">
                                            <a href="<?php echo $post->getPostUrlWithNoCategory(); ?>"><?php echo __('Read more') ?></a>
                                        </div>
            <?php endif ?>
                                </div>
                            </div>

                            <?php $j++; ?>
        <?php endforeach; ?>                        
                    </div>
                    <div class="col-md-6">
                        <?php
                        $i = 0;
                        foreach ($collection as $post): $i++;
                            ?>  
                            <?php if ($i == 1): ?>
                                    <?php continue; ?>
                                <?php endif; ?>
                            <div class="item">
                                <?php if ($showThumbnail): ?>
                                    <div class="image post-left"><?php echo $helper->getThumbnailPost($post); ?></div>
            <?php endif ?>
                                <div class="post-right">
                                    <div class="post-meta">
                                        <p class="h6"><?php echo __('%1', $block->formatDate($post->getCreatedAt(), \IntlDateFormatter::MEDIUM, false)); ?></p>
                                    </div>
                                    <h4 class="title"><a href="<?php echo $post->getPostUrlWithNoCategory(); ?>" title="<?php echo $post->getTitle(); ?>"><?php echo $post->getTitle() ?></a></h4>
                                        <?php if ($showShortContent): ?>
                                        <div class="short-content">
                <?php echo substr($post->getShortContent(), 0, $this->getConfig('limit_characters_short_content')) . '...'; ?>
                                        </div>
                                        <div class="read-more">
                                            <a href="<?php echo $post->getPostUrlWithNoCategory(); ?>"><?php echo __('Read more') ?></a>
                                        </div>
            <?php endif ?>
                                </div>

                            </div>

        <?php endforeach ?>
                    </div>
                </div>

            </div>
        <?php endif; ?>

    <?php else: ?>
        <div role="alert" class="alert alert-warning"> <?php echo __('There are no posts matching the selection.') ?> </div>
<?php endif; ?>
</div>
