<?php $_productCollection = $this->getDealsByCategories($this->getCategoryIds()) ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<div class="content-block deal-product-cat-block">
	<?php if($this->hasData('mgs_panel_title')): ?>
		<div class="content-heading">
			<h2 class="title"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></h2>
		</div>
	<?php endif ?>
	
	<?php if (count($_productCollection)>0): ?>
		<?php if($this->hasData('mgs_panel_note')): ?>
			<div class="block-note"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_note')) ?></div>
		<?php endif ?>
		
		<?php 
			$blockId = rand() . time();
			$_helper = $this->helper('Magento\Catalog\Helper\Output');
			$useSlider = $this->getUseSlider();
			$perRow = $this->getPerrow();
			$image = 'category_page_grid';
			$themeSettings = $themeHelper->getThemeSettings();
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			$col = $themeHelper->convertPerRowtoCol($perRow);
			$autoPlay = $this->getAutoplay() ? 'true' : 'false';
			$stopAuto = $this->getStopAuto() ? 'true' : 'false';
			$nav = $this->getNavigation() ? 'true' : 'false';
			$dot = $this->getPagination() ? 'true' : 'false';
		?>
		
		<div class="block widget mgs-products deal-products-grid">
			<div class="items<?php if($useSlider): ?> owl-carousel<?php else: ?> row <?php echo $themeHelper->convertColClass($col, 'row') ?><?php endif ?>" id="deal-products<?php echo $blockId; ?>">
				<?php foreach ($_productCollection as $_product): ?>
					<div class="item product product-item<?php if(!$useSlider): ?> <?php echo $themeHelper->convertColClass($col, 'col') ?><?php endif ?>">
						<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
						<div class="product-item-info" data-container="product-grid">
							<?php
								$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
								$size = $themeHelper->getImageSize($this->getRatio());
								$productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();
							?>
							<?php // Product Image ?>
							<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<img src="<?php echo $productImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo img-thumbnail"/>
								<?php echo $themeHelper->getProductLabel($_product) ?>
							</a>
							<div class="product details product-item-details">
								
								<strong class="product name product-item-name">
									<a class="product-item-link"
									   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
										<h4><?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></h4>
									</a>
								</strong>
								<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
								<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
								<?php echo $block->getProductDetailsHtml($_product); ?>
								<?php echo $this->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setProduct($_product)->setTemplate('Magento_Swatches::product/listing/renderer.phtml')->toHtml() ?>

								<div class="product-item-inner">
									<div class="product actions product-item-actions">
										<div class="actions-primary">
											<?php if ($_product->isSaleable()): ?>
												<?php $postParams = $block->getAddToCartPostParams($_product); ?>
												<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
													<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
													<input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
													<input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
													<button class="action tocart btn-cart btn btn-primary" type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
														<span><span class="fa fa-shopping-cart"></span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
													</button>
													
												</form>
											<?php else: ?>
												<?php if ($_product->getIsSalable()): ?>
													<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
												<?php else: ?>
													<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
												<?php endif; ?>
											<?php endif; ?>
										</div>
										<?php if(!$themeSettings['catalog']['wishlist_button'] || !$themeSettings['catalog']['compare_button']): ?>
											<div data-role="add-to-links" class="actions-secondary">
												<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$themeSettings['catalog']['wishlist_button']): ?>
													<a href="#"
													   class="action towishlist btn btn-default"
													   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
													   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
													   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
													   data-action="add-to-wishlist"
													   role="button">
														<i class="fa fa-heart"></i>
													</a>
												<?php endif; ?>
												<?php
												$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
												?>
												<?php if(!$themeSettings['catalog']['compare_button']): ?>
													<a href="#"
													   class="action tocompare btn btn-default"
													   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
													   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
													   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
													   role="button">
														<i class="fa fa-random"></i>
													</a>
												<?php endif ?>
											</div>
										<?php endif ?>
										
										<div class="li-quickview">
											<?php /* Append Quick View */ ?>
											<?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
											<?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?>
										</div>
									</div>
								</div>
								
								<?php echo $this->getLayout()->createBlock('MGS\Mpanel\Block\Products\Deals')->setProduct($_product)->setTemplate('MGS_Mpanel::products/deals/item.phtml')->toHtml() ?>
							</div>
						</div>
					</div>
				<?php endforeach; ?>
			</div>
			
			<?php if($useSlider): ?>
				<script type="text/javascript">
					require([
						'jquery',
						'mgs/owlcarousel'
					], function ($) {
						$('#deal-products<?php echo $blockId ?>').owlCarousel({
							items: <?php echo $perRow; ?>,
							autoplay: <?php echo $autoPlay ?>,
							autoplayHoverPause: <?php echo $stopAuto ?>,
							nav: <?php echo $nav ?>,
							dots: <?php echo $dot ?>,
							margin:30,
							responsive:{
								0:{
									items:1,
									margin:0
								},
								480:{
									items:2,
									margin:20
								},
								768:{
									items:<?php echo $perRow; ?>
								}
							}
						});
					});
				</script>
			
			<?php endif ?>
		</div>
		
	<?php else: ?>
		<div role="alert" class="alert alert-warning"><?php echo __('There are no deals matching the selection.') ?></div>
	<?php endif ?>
</div>