<?php $_product = $this->getProduct() ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<div class="content-block single-product">
    <?php if ($this->getData('mgs_panel_title')): ?>
        <div class="title-block">
            <h2 class="title"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></h2>
            <?php if ($this->getData('mgs_panel_note')): ?>
                <div class="block-note"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_note')) ?></div>
            <?php endif ?>
        </div>
    <?php endif ?>

    <?php if ($_product && $_product->getId()): ?>	

        <?php
        $_helper = $this->helper('Magento\Catalog\Helper\Output');
        $themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
        $image = 'category_page_grid';
        $themeSettings = $themeHelper->getThemeSettings();
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        ?>

        <div class="block widget mgs-product">
            <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
            <div class="product-item-info" data-container="product-grid">
                <?php
                $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
                $size = $themeHelper->getImageSize($this->getRatio());
                $productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();
                ?>
                <?php // Product Image ?>
                <div class="product-image">
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <img src="<?php echo $productImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo"/>
                        <?php echo $themeHelper->getProductLabel($_product) ?>
                    </a>
                </div>
                <div class="product details product-item-details">
                    <!-- Show Product Name -->
                    <?php if ($this->getProductName()): ?>
                        <div class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <h4><?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></h4>
                            </a>
                        </div>
                    <?php endif ?>

                    <!-- Show Rating -->
                    <?php if ($this->getProductRating()): ?>
                        <?php $product = $this->getLoadProduct($_product->getId()) ?>
                        <?php echo $block->getReviewsSummaryHtml($product, $templateType, true); ?>
                    <?php endif ?>

                    <!-- Show Product Price -->
                    <?php if ($this->hasData('product_price') && $this->getData('product_price')): ?>
                        <?php echo $block->getProductPrice($_product) ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>
                    <?php endif ?>
                    <!-- Show Categories link -->
                    <?php if ($this->hasData('product_categories') && $this->getData('product_categories')): ?>
                        <div class="categories-link"><span class="label"><?php echo __('Categories') ?></span><span class="value"><?php echo $this->getCategoriesLink($_product) ?></span></div>
                    <?php endif ?>
                        <!-- Show Short Description -->
                        <?php if ($this->hasData('product_description') && $this->getData('product_description')): ?>
                            <?php if ($this->hasData('characters_count') && ($this->getData('characters_count') != '') && ($this->getData('characters_count') > 0)): ?>
                                <?php $description = $themeHelper->truncate($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'), $this->getData('characters_count')) ?>
                            <?php else: ?>
                                <?php $description = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                            <?php endif ?>
                            <div class="product description"><?php echo $description ?></div>
                        <?php endif ?>
                    <div class="product-item-inner">
                        <div class="product actions product-item-actions">

                            <!-- Show Add to cart -->
                            <?php if ($this->getProductAddcart()): ?>
                                
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
                                            <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
                                            <button class="action tocart btn-cart btn btn-primary" type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                <span class="text"><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>

                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                               
                            <?php endif ?>
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$themeSettings['catalog']['wishlist_button']): ?>
                                        <a href="#"
                                           class="action towishlist btn btn-addto"
                                           title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                           data-action="add-to-wishlist"
                                           role="button">
                                            <i class="ion-heart"></i>
                                        </a>
                                    <?php endif; ?>
                                    <?php
                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                    ?>
                                    <?php if (!$themeSettings['catalog']['compare_button']): ?>
                                        <a href="#"
                                           class="action tocompare btn btn-addto"
                                           title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                           role="button">
                                            <i class="ion-shuffle"></i>
                                        </a>
                                    <?php endif ?>
                                <?php /* Append Quick View */ ?>
                                <?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
                                <?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>

    <?php else: ?>
        <div role="alert" class="alert alert-warning"><?php echo __('There are no product matching the selection.') ?></div>
    <?php endif ?>
</div>