<?php $_productCollection = $this->getNewProductByCategories($this->getCategoryIds()) ?>
<?php $_collectionSize = $_productCollection->count() ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>

<div class="content-block new-products-block new-products-list-block list-block-products">
    <?php if ($this->getData('mgs_panel_title')): ?>
        <div class="content-heading">
            <h2 class="title"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></h2>
        </div>
    <?php endif ?>

    <?php if ($_collectionSize): ?>
        <?php if ($this->getData('mgs_panel_note')): ?>
            <div class="block-note"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_note')) ?></div>
        <?php endif ?>

        <?php
        $blockId = rand() . time();
        $_helper = $this->helper('Magento\Catalog\Helper\Output');
        $useSlider = $this->getUseSlider();
        $perRow = $this->getPerrow();
        $image = 'category_page_grid';
        $themeSettings = $themeHelper->getThemeSettings();
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        $col = $themeHelper->convertPerRowtoCol($perRow);
        $autoPlay = $this->getAutoplay() ? 'true' : 'false';
        $stopAuto = $this->getStopAuto() ? 'true' : 'false';
        $nav = $this->getNavigation() ? 'true' : 'false';
        $dot = $this->getPagination() ? 'true' : 'false';
        ?>

        <?php if ($useSlider): ?>

            <div class="block widget list-products mgs-new-products-list-carousel">
                <div class="owl-carousel mgs-carousel-<?php echo $blockId; ?> product-items">
                    <?php $i = 0;
                    foreach ($_productCollection as $_product): ?>
                            <?php if ($i++ % $perRow == 0): ?>
                            <div class="item">
                                <?php endif ?>
                            <div class="new-products-content list-content  product-item">
                                    <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                                <div class="product-item-info" data-container="product-grid">
                                    <?php
                                    $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
                                    $size = $themeHelper->getImageSize($this->getRatio());
                                    $productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();
                                    ?>
            <?php // Product Image  ?>
                                    <div class="product-top">
                                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                            <img src="<?php echo $productImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo"/>

                                        </a>
                                        <div class="product-item-inner">
                                            <div class="product actions product-item-actions">
                                                <?php if ($_product->isSaleable()): ?>
                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                        <input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
                                                        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
                                                        <button class="action tocart btn-cart btn btn-primary" type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span class="ion-ios-cart icon"></span>
                                                        </button>

                                                    </form>
                                                <?php else: ?>
                                                    <?php if ($_product->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
            <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product details product-item-details">

                                        <div class="product name product-item-name">
                                            <a class="product-item-link"
                                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                                <h4><?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></h4>
                                            </a>
                                        </div>
                                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                        <div class="meta-box">
                                            <?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
                                            <div class="product-box-label">
                                            <?php echo $themeHelper->getProductLabel($_product) ?>
                                            </div>
            <?php echo $this->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setProduct($_product)->setTemplate('Magento_Swatches::product/listing/renderer.phtml')->toHtml() ?>
                                        </div>


            <?php //echo $block->getProductDetailsHtml($_product);   ?>


                                    </div>
                                </div>
                            </div>
                        <?php if ($i % $perRow == 0 || $i == $_collectionSize): ?>
                            </div>
                        <?php endif ?>
        <?php endforeach ?>
                </div>
            </div>
            <script type="text/javascript">
                require([
                    'jquery',
                    'mgs/owlcarousel'
                ], function ($) {
                    $('.mgs-carousel-<?php echo $blockId ?>').owlCarousel({
                        items: 1,
                        autoplay: <?php echo $autoPlay ?>,
                        autoplayHoverPause: <?php echo $stopAuto ?>,
                        nav: <?php echo $nav ?>,
                        navText: ['<span class="ion-ios-arrow-left"></span>', '<span class="ion-ios-arrow-right"></span>'],
                        dots: <?php echo $dot ?>,
                    });
                });
            </script>
    <?php else: ?>
            <div class="block widget list-products mgs-new-products new-products-list">
                <div class="block-content">
                    <ul class="product-items">
                            <?php foreach ($_productCollection as $_product): ?>
                            <li class="new-products-content list-content product-item ">
                                <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                                <?php
                                $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
                                $size = $themeHelper->getImageSize($this->getRatio());
                                $productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();
                                ?>
								<div class="product-item-info" data-container="product-grid">
            <?php // Product Image  ?>
                                <div class="product-top">
                                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                        <img src="<?php echo $productImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo"/>

                                    </a>
                                    <div class="product-item-inner">
                                        <div class="product actions product-item-actions">
                                            <?php if ($_product->isSaleable()): ?>
                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                    <input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
                                                    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
                                                    <button class="action tocart btn-cart btn btn-primary" type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span class="ion-ios-cart icon"></span>
                                                    </button>

                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="product details product-item-details">

                                    <div class="product name product-item-name">
                                        <a class="product-item-link"
                                           href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                            <h4><?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></h4>
                                        </a>
                                    </div>
                                    <div class="box-meta">
                                            <?php //echo $block->getReviewsSummaryHtml($_product, $templateType);  ?>
                                        <div class="product-box-label">
                                        <?php echo $themeHelper->getProductLabel($_product) ?>
                                        </div>                                        
                                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                        <?php //echo $block->getProductDetailsHtml($_product); ?>
            <?php echo $this->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setProduct($_product)->setTemplate('Magento_Swatches::product/listing/renderer.phtml')->toHtml() ?>
                                    </div>

                                </div>
								</div>
							</li>
        <?php endforeach ?>
                    </ul>
                </div>
            </div>
        <?php endif ?>

    <?php else: ?>
        <div role="alert" class="alert alert-warning"><?php echo __('There are no products matching the selection.') ?></div>
<?php endif ?>
</div>