<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright">
    <div><?= /* @escapeNotVerified */ $block->getCopyright() ?></div>
    <div>Designed & Developed by <a target="_blank" href="https://akeans.com/">Akeans Softwares</a></div>
    <style>
    .footer-bottom .container > .row{display: flex; align-items: center; flex-wrap: wrap;}
    </style>
</small>
