
<?php $_storeView = $this->getStoreView(); ?>

    <div class="storelocator-details">
        <div id="map-detail"></div>
        <div class="store-info-detail">
                <div class="box-store-content col-md-6 col-xs-12">
                        <h3><?php echo $this->escapeHtml($_storeView->getName()) ?></h3>
							<table class="table portfolio-table table-hover">
								<tbody>
									<tr>
									    <?php if ($imageUrl = $_storeView->getImageUrl()): ?>
										    <td colspan="2" class="text-center"><img class="img-responsive" src="<?php echo $imageUrl ?>" alt="<?php echo $_storeView->getName() ?>" title="<?php echo $_storeView->getName() ?>"/></td>
										<?php endif; ?>
									</tr>
									<tr>
										<td><?php echo __('Address:') ?></td>
										<td><?php echo $_storeView->getStreetAddress().' '.ucfirst($_storeView->getCity()).' '.ucfirst($_storeView->getState()).' '.$_storeView->getZipcode().' '.$_storeView->getCountry() ?> </td>
									</tr>
									<tr>
									    <?php if($_storeView->getEmail()): ?>
											<td><?php echo __('Email:') ?></td>
											<td><a href="mailto:<?php echo $this->escapeHtml($_storeView->getEmail()) ?>"><?php echo $this->escapeHtml($_storeView->getEmail()) ?></a></td>
										<?php endif; ?>
									</tr>
									<tr>
									    <?php if($_storeView->getFax()): ?>
											<td><?php echo __('Fax:') ?></td>
											<td><?php echo $this->escapeHtml($_storeView->getFax()) ?></td>
									    <?php endif; ?>
									</tr>
									<tr>
									    <?php if($_storeView->getPhone()): ?>
											<td><?php echo __('Phone:') ?></td>
											<td><a href="tel:<?php echo $this->escapeHtml($_storeView->getPhone()) ?>"><?php echo $this->escapeHtml($_storeView->getPhone()) ?></a></td>
									    <?php endif; ?>
									</tr>
									<tr>
									    <?php if($_storeView->getWebsite()): ?>
											<td><?php echo __('Website:') ?></td>
											<td><a href="<?php echo $_storeView->getWebsite() ?>"><?php echo $_storeView->getWebsite() ?></a></td>
									    <?php endif; ?>
									</tr>
								</tbody>
							</table>
					</div>

                <?php if($_storeView->getDescription()): ?>
                    <div class="store-html-content store-description col-md-3 col-xs-12">
                        <h3><?php echo __('Store Information') ?></h3>
                        <div class="content">
                            <?php echo $this->getDescription(); ?>
                        </div>
                    </div>
                <?php endif ?>

                <?php if($_storeView->getTradingHours()): ?>
                    <div class="store-html-content store-opening-hours col-md-3 col-xs-12">
                        <h3><?php echo __('Opening Hours') ?></h3>
                        <div class="content">
                            <?php echo $this->getTradingHours(); ?>
                        </div>
                    </div>
                <?php endif ?>
        </div>
		<div class="back clearfix">
             <button onclick="window.location= '<?php echo $block->getUrl('locator/') ?>';" class="action primary btn btn-primary btn-custom" title="<?php echo __('Back') ?>" type="button">
                  <span><?php echo __('Back') ?></span>
             </button>
        </div>
    </div>
<?php
//Get store google map related information
$storeName = $_storeView->getName();
$storeLat = $_storeView->getLat();
$storeLong = $_storeView->getLng();
$storeRadius = $this->getRadius($_storeView);
?>
<?php if($storeLat && $storeLong): ?>
    <script>
        require(['jquery', 'MGS_StoreLocator/js/storelocator'], function($) {
            $(window).load(function() {
                var storeLat = <?php echo $storeLat ;?>;
                var storeLong = <?php echo $storeLong ;?>;
                var storeRadius = <?php echo $storeRadius ;?>;
                var storeInfoText = '<div class="map-short-info"><h3><?php echo $storeName ; ?></h3><p><?php echo $_storeView->getStreetAddress() ?> <?php echo $_storeView->getCity() ?> <?php echo $_storeView->getState() ?> <?php echo $_storeView->getZipcode() ?> <?php echo $_storeView->getCountry() ?></p>';
                var googleMapDivId = 'map-detail';
                google.maps.event.addDomListener(window, 'load', initializeMap(storeLat, storeLong, storeRadius, storeInfoText, googleMapDivId));
            });
        });
    </script>
<?php endif ?>