<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
/** @var \Magento\Bundle\Pricing\Render\FinalPriceBox $block */
$productId = $block->getSaleableItem()->getId();
/** @var \Magento\Bundle\Pricing\Price\FinalPrice $finalPriceModel */
$finalPriceModel = $block->getPrice();
$minimalPrice = $finalPriceModel->getMinimalPrice();
$maximalPrice = $finalPriceModel->getMaximalPrice();
/** ex: \Magento\Bundle\Pricing\Price\BundleRegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $regularPriceModel */
$regularPriceModel = $block->getPriceType('regular_price');
$maximalRegularPrice = $regularPriceModel->getMaximalPrice();
$minimalRegularPrice = $regularPriceModel->getMinimalPrice();
?>
<?php if ($block->getSaleableItem()->getPriceView()): ?>

    <p class="minimal-price">
         <?php if ($minimalPrice < $minimalRegularPrice): ?>
            <span class="old-price">
                <?php /* @escapeNotVerified */ echo $block->renderAmount($minimalRegularPrice, [
                    'display_label'     => __('Regular Price'),
                    
                    'include_container' => true,
                    'skip_adjustments'  => true
                ]); ?>
            </span>
        <?php endif ?>
        <?php /* @escapeNotVerified */ echo $block->renderAmount($minimalPrice, [
            'display_label'     => __('As low as'),
            
            'include_container' => true
        ]); ?>
       
    </p>
<?php else: ?>
    <?php if ($block->showRangePrice()): ?>
        <p class="price-from">
             <?php if ($minimalPrice < $minimalRegularPrice): ?>
                <span class="old-price">
                    <?php /* @escapeNotVerified */ echo $block->renderAmount($minimalRegularPrice, [
                        'display_label'     => __('Regular Price'),
                        
                        'include_container' => true,
                        'skip_adjustments'  => true
                    ]); ?>
                </span>
            <?php endif ?>
            <?php /* @escapeNotVerified */ echo $block->renderAmount($minimalPrice, [
                'display_label'     => __('From'),
                
                'price_type'        => 'minPrice',
                'include_container' => true
            ]); ?>
           
        </p>
        <p class="price-to">
            <?php if ($maximalPrice < $maximalRegularPrice): ?>
                <span class="old-price">
                    <?php /* @escapeNotVerified */ echo $block->renderAmount($maximalRegularPrice, [
                        'display_label'     => __('Regular Price'),
                        
                        'include_container' => true,
                        'skip_adjustments'  => true
                    ]); ?>
                </span>
            <?php endif ?>
            <?php /* @escapeNotVerified */ echo $block->renderAmount($maximalPrice, [
                'display_label'     => __('To'),
                
                'price_type'        => 'maxPrice',
                'include_container' => true
            ]); ?>
            
        </p>
    <?php else: ?>
         <?php if ($minimalPrice < $minimalRegularPrice): ?>
            <span class="old-price">
                <?php /* @escapeNotVerified */ echo $block->renderAmount($minimalRegularPrice, [
                    'display_label'     => __('Regular Price'),
                    
                    'include_container' => true,
                    'skip_adjustments'  => true
                ]); ?>
            </span>
        <?php endif ?>
        <?php /* @escapeNotVerified */ echo $block->renderAmount($minimalPrice, [
           
            'include_container' => true
        ]); ?>
       
    <?php endif ?>
<?php endif ?>
