<?php
/**
* Copyright 2016 aheadWorks. All rights reserved.
* See LICENSE.txt for license details.
*/

/* @var $block \Aheadworks\Helpdesk\Block\Sales\Order\CreateTicketLink */

// @codingStandardsIgnoreFile
?>
<a class="action aw-helpesk-create-link" href="<?php echo $block->escapeUrl($block->getActionUrl()) ?>">
    <span><?php echo $block->escapeHtml(__('Submit Support Ticket')) ?></span>
</a>
