<?php $block = $this->getBlock() ?>
<?php $helper = $this->helper('MGS\Mpanel\Helper\Data') ?>
<?php $canUsePanel = $helper->acceptToUsePanel() ?>
<?php $welcomeMessage = $block->getWelcome();
$_isCheckHome = $block->getLayout()->createBlock('\Magento\Theme\Block\Html\Header\Logo')->isHomePage();
?>
<div class="middle-header-container">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2 col-sm-6 col-xs-6 header-left"><?php if($this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('panel_logo_sticky')->toHtml()): ?><div class="hidden-logo"><?php endif;?><?php echo $block->getChildHtml('logo') ?><?php if($this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('panel_logo_sticky')->toHtml()): ?></div><?php endif;?>
                        <?php if($helper->getStoreConfig('mgstheme/general/sticky_menu') && $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('panel_logo_sticky')->toHtml()): ?>
                        <div class="logo-sticky"><a href="<?php echo $this->getBaseUrl();?>"><?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('panel_logo_sticky')->toHtml();?></a></div>
                        <?php endif;?></div>
            <div class="col-md-8 hidden-sm hidden-xs">
                <?php echo $block->getChildHtml('megamenu') ?>                
            </div>
            <div class="col-md-2 col-sm-6 col-xs-6 header-right pull-right">
                <div class="box-topbar">
                    <span class="nav-toggle"><i class="ion-navicon"></i></span>
                    <?php echo $block->getChildHtml('minicart') ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="top-bar-abs">
    <span class="nav-toggle-close"><i class="ion-ios-close-empty"></i></span>
    <div class="greet welcome" data-bind="scope: 'customer'">
        <span data-bind="text: customer().fullname ? $t('Welcome, %1!').replace('%1', customer().fullname) : '<?php echo $block->escapeHtml($welcomeMessage) ?>'"><?php echo $block->escapeHtml($welcomeMessage) ?></span>
    </div>
    <div class="language-current">
        <?php echo $block->getChildHtml('store_language') ?>
        <?php echo $block->getChildHtml('currency') ?>
        <div class="account-dropdown" id="top-links">
            <a href="#" class="action toggle top-links-trigger" id="top-links-trigger">
                <i class="fa fa-user"></i>
            </a>
            <div class="dropdown top-links-dropdown" style="display:none;" data-mage-init='{"dropdownDialog":{
                 "appendTo":"#top-links",
                 "triggerTarget":"#top-links-trigger",
                 "closeOnMouseLeave":false,
                 "triggerClass":"active",
                 "parentClass":"active",
                 "buttons":null,
                 "defaultDialogClass":"dropdown-menu"}}'>  
                     <?php echo $block->getChildHtml('top.links') ?>
            </div>
        </div>  
    </div>
    <div class="top-header-links">		
        <span class="h4"><?php echo __('Usefull Links') ?></span>
        <?php echo $block->getChildHtml('megamenu') ?>
    </div>
    <div class="hidden-sm hidden-xs">
        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('organie_block_social_header')->setCanUsePanel($canUsePanel)->toHtml() ?>
    </div>                                                

    <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Search::form.mini.phtml")->toHtml();?>

</div>
