<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="content">
	<form class="form subscribe"
		novalidate
		action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
		method="post"
		data-mage-init='{"validation": {"errorClass": "mage-error"}}'
		id="newsletter-validate-detail">
		<div class="field newsletter">
		
			<div class="control">
				<input class="input-text form-control input-lg" name="email" type="email" id="newsletter"
							placeholder="<?php /* @escapeNotVerified */ echo __('Enter your e-mail') ?>"
							data-validate="{required:true, 'validate-email':true}"/>
			</div>
		</div>
		<div class="actions">
			<button class="action subscribe primary btn btn-primary btn-lg" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
				<span class="hidden-xs"><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
				<span class="fa fa fa-paper-plane hidden-lg hidden-md hidden-sm"></span>
			</button>
		</div>
	</form>
</div>
