<div id="back-top" class="hidden-xs"><i class="fa fa-angle-double-up"></i></div>

<div class="footer-container">

	<div class="footer-static-container">

		<div class="container">

			<?php echo $this->getChildHtml("footer_static"); ?>

		</div>

	</div>

	<div class="footer-bottom">

		<div class="container">

			<div class="row">

				<div class="col-md-4 col-xs-12">
					<?php echo $this->getChildHtml("copyright"); ?>
				</div>
                <div class="col-md-4 col-xs-12">
					<?= $block->getChildHtml('store_switcher') ?>
				</div>
				<div class="col-md-4 col-xs-12">
					<?php echo $this->getChildHtml("social_block"); ?>
				</div>

			</div>

			<div class="row">

				<div class="col-md-12 col-xs-12">

				<?php

					echo $this->getLayout()

					->createBlock('Magento\Cms\Block\Block')

					->setBlockId('footer_bottom_links')

					->toHtml();

				?>

				</div>

			</div>

		</div>

	</div>

</div>

<script>

	window.onload = function () {

		document.body.className += " preloaded";

	}

</script>