<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php 
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$themeSettings = $themeHelper->getThemeSettings();
?>
	<?php if($this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('organie_contact_information_2')->toHtml()): ?>
		 <section class="store-information">
		     <div class="container">
			    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('organie_contact_information_2')->toHtml();?>
		     </div>
		 </section>
	<?php endif ?>
	<section class="map">
		  <?php echo $this->getLayout()->createBlock("Magento\Contact\Block\ContactForm")->setTemplate("Magento_Contact::map.phtml")->toHtml();?>
	</section>
	<section class="form_contact">
	    <div class="col-md-8 col-sm-12 col-md-offset-2">
		<form class="form contact"
		  action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
		  id="contact-form"
		  method="post"
		  data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
		  data-mage-init='{"validation":{}}'>
			            <div class="title_section text-center">
					       <h2 class="text-uppercase">Leave us a message</h2>
					       <em class="h5 base-color">-Good for nature, good for you-</em>
				        </div>
					<div class="form-groups">
						<div class="form-group control-icon name required col-lg-4 col-md-4 col-sm-12 col-xs-12">
							<input placeholder="<?php echo __('Name'); ?>" name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text form-control" type="text" data-validate="{required:true}"/>
						</div>
						<div class="form-group control-icon email required col-lg-4 col-md-4 col-sm-12 col-xs-12">
							<input placeholder="<?php echo __('E-mail *'); ?>" name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text form-control" type="email" data-validate="{required:true, 'validate-email':true}"/>
						</div>
						<div class="form-group control-icon Telephone col-lg-4 col-md-4 col-sm-12 col-xs-12">
							<input placeholder="<?php echo __('Telephone'); ?>" name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Telephone') ?>" value="" class="input-text form-control" type="text" />
						</div>
						<div class="form-group control-icon comment required">
							<textarea placeholder="<?php /* @escapeNotVerified */ echo __('Comment*') ?>" name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('Comment') ?>" class="input-text form-control" cols="5" rows="9" data-validate="{required:true}"></textarea>
						</div>
					</div>
						<div class="actions-toolbar">
							<input type="hidden" name="hideit" id="hideit" value="" />
							<button type="submit" title="<?php /* @escapeNotVerified */ echo __('Post comment') ?>" class="action submit btn btn-custom btn-primary">
								<span><?php /* @escapeNotVerified */ echo __('Post comment') ?></span>
							</button>
						</div>
		</form>
		</div>
	</section>