<?php $categories = $this->getCategoryByIds() ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<div class="content-block deal-product-cat-block deal-product-cat-tab-block">
	<?php if($this->getData('mgs_panel_title')): ?>
		<div class="title-block">
                    <h2 class="title"><span><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></span></h2>
			<?php if($this->getData('mgs_panel_note')): ?>
				<div class="block-note"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_note')) ?></div>
			<?php endif ?>
		</div>
	<?php endif ?>
	
	<?php if(count($categories)>0): ?>
		

		<?php 
			$blockId = rand() . time();
			$_helper = $this->helper('Magento\Catalog\Helper\Output');
			$useSlider = $this->getUseSlider();
			$perRow = $this->getPerrow();
			$image = 'category_page_grid';
			$themeSettings = $themeHelper->getThemeSettings();
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			$col = $themeHelper->convertPerRowtoCol($perRow);
			$autoPlay = $this->getAutoplay() ? 'true' : 'false';
			$stopAuto = $this->getStopAuto() ? 'true' : 'false';
			$nav = $this->getNavigation() ? 'true' : 'false';
			$dot = $this->getPagination() ? 'true' : 'false';
		?>
		<div class="tabbable">
			<ul class="nav nav-tabs">
				<?php $i=0; foreach($categories as $category): $i++ ?>
					<li<?php if($i==1): ?> class="active"<?php endif ?>>
						<a data-toggle="tab" href="#category-tab-<?php echo $category->getId().$blockId ?>"><?php echo $category->getName(); ?></a>
					</li>
				<?php endforeach ?>
			</ul>
			<div class="tab-content">
				<?php $i=0; foreach($categories as $category): $i++ ?>
					<div id="category-tab-<?php echo $category->getId().$blockId ?>" class="tab-pane<?php if($i==1): ?>  active<?php endif ?><?php if($useSlider): ?> product-carousel<?php endif ?>">
						<div class="deal-product-category-tab" id="category<?php echo $category->getId().$blockId; ?>-deal-products">
							<?php $_productCollection = $this->getProductCollection($category); ?>
							<?php if (count($_productCollection)>0): ?>
								<div class="block widget mgs-products  deal-products-grid <?php if ($perRow > 1): ?> custom-deal <?php endif; ?>">
									<!-- Don't Remove Id of this div element -->
									<div class="items<?php if($useSlider): ?> owl-carousel<?php else: ?> row <?php echo $themeHelper->convertColClass($col, 'row') ?><?php endif ?>" id="deal-products<?php echo $category->getId().$blockId; ?>">
										<?php foreach ($_productCollection as $_product): ?>
											<div class="item product product-item<?php if(!$useSlider): ?> <?php echo $themeHelper->convertColClass($col, 'col') ?><?php endif ?>">
												<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
												<div class="product-item-info <?php if ($perRow == 1): ?> row<?php endif; ?>" data-container="product-grid">
													<?php
														$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
														$size = $themeHelper->getImageSize($this->getRatio());
														$productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();
													?>
													<?php // Product Image ?>
													<?php if ($perRow == 1): ?><div class="col-md-6 col-sm-12 col-xs-12"><?php endif; ?>
                                <div class="product-photo">
                                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                        <img src="<?php echo $productImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo"/>

                                    </a> <div class="box-deal-label">
                                        <span class="h6"><?php echo __('Only'); ?></span>
                                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                    </div>
                                </div>
                                <?php if ($perRow == 1): ?></div><?php endif; ?>
													<?php if ($perRow == 1): ?><div class="col-md-6 col-sm-12 col-xs-12 product-desc"><?php endif; ?>
                                <div class="product details product-item-details">
                                    <div class="product name product-item-name">
                                        <a class="product-item-link"
                                           href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                            <h5><?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></h5>
                                        </a>
                                    </div>
                                    <div class="short-description"><?php echo $_product->getDescription(); ?></div>
                                    <?php
                                    $_categories = $_product->getCategoryIds();
                                    ?>
                                    <?php if($_categories || $_product->getWeight() || $_product->getData('expire_date'))?>
                                    <div class="box-attribute">
                                        <?php if ($_categories): ?>
                                            <dl>
                                                <dt><?php echo __('Categories') ?></dt>
                                                <dd> <?php
                                                    $j = 0;
                                                    foreach ($_categories as $category_id): $j++;
                                                        ?>
                                                        <?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
                                                        <?php $currentCate = $objectManager->create('Magento\Catalog\Model\Category')->load($category_id); ?>
                                                        <a href="<?php echo $currentCate->getUrl(); ?>"><?php echo $currentCate->getName(); ?></a><?php if ($j != count($_categories)): ?><span>,</span><?php endif ?>
                                                    <?php endforeach; ?>
                                                </dd>
                                            </dl>
                                        <?php endif; ?>
                                        <?php if ($_product->getWeight()): ?>
                                            <dl>
                                                <dt><?php echo __('Weight'); ?></dt>
                                                <dd><?php echo number_format($_product->getWeight(), 1, ',', '') ?> <?php echo __('kg/package'); ?></dd>
                                            </dl>
                                        <?php endif; ?>
                                        <?php if ($_product->getData('expire_date')): ?>
                                            <dl>
                                                <dt><?php echo __('Expire Date'); ?></dt>
                                                <dd><?php echo __('%1', $block->formatDate($_product->getData('expire_date'), \IntlDateFormatter::SHORT, false)); ?></dd>
                                            </dl>
                                        <?php endif; ?>

                                    </div>
                                    <?php //echo $block->getProductDetailsHtml($_product); ?>
                                    <?php //echo $this->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setProduct($_product)->setTemplate('Magento_Swatches::product/listing/renderer.phtml')->toHtml() ?>
                                    <?php echo $this->getLayout()->createBlock('MGS\Mpanel\Block\Products\Deals')->setProduct($_product)->setTemplate('MGS_Mpanel::products/deals/item.phtml')->toHtml() ?>
                                    <div class="product-item-inner">
                                        <div class="product actions product-item-actions">
                                           
                                                <?php if ($_product->isSaleable()): ?>
                                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                        <input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
                                                        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
                                                        <button class="action tocart btn-cart btn btn-primary" type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
														
                                                            <span class="text"><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></div>
														
                                                        </button>
                                                    </form>
                                                <?php else: ?>
                                                    <?php if ($_product->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            
                                            <?php if (!$themeSettings['catalog']['wishlist_button'] || !$themeSettings['catalog']['compare_button']): ?>                                               
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$themeSettings['catalog']['wishlist_button']): ?>
                                                        <a href="#"
                                                           class="action towishlist btn btn-addto"
                                                           title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                           aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                           data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                                           data-action="add-to-wishlist"
                                                           role="button">
                                                            <i class="ion-heart"></i>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php
                                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                    ?>
                                                    <?php if (!$themeSettings['catalog']['compare_button']): ?>
                                                        <a href="#"
                                                           class="action tocompare btn btn-addto"
                                                           title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                           aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                           data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                                           role="button">
                                                            <i class="ion-shuffle"></i>
                                                        </a>
                                                    <?php endif ?>
                                                
                                            <?php endif ?>
                                        </div>
                                    </div>
                                </div>
                                <?php if ($perRow == 1): ?></div><?php endif; ?>
													</div>
											</div>
										<?php endforeach; ?>
									</div>
									<?php if($useSlider): ?>
										<script type="text/javascript">
											require([
												'jquery',
												'mgs/owlcarousel'
											], function ($) {
												$('#deal-products<?php echo $category->getId().$blockId ?>').owlCarousel({
													items: <?php echo $perRow; ?>,
													autoplay: <?php echo $autoPlay ?>,
													autoplayHoverPause: <?php echo $stopAuto ?>,
													nav: <?php echo $nav ?>,
													navText: ['<span class="ion-ios-arrow-left"></span>', '<span class="ion-ios-arrow-right"></span>'],
													dots: <?php echo $dot ?>,
													margin:30,
													responsive:{
														0:{
															items:1,
															margin:0
														},
														480:{
															items:2,
															margin:20
														},
														768:{
															items:<?php echo $perRow; ?>
														}
													}
												});
											});
										</script>
										
									<?php endif ?>
								</div>
							<?php else: ?>
								<div role="alert" class="alert alert-warning"> <?php echo __('The category "%1" haven\'t deal.', $category->getName()) ?> </div>
							<?php endif ?>
						</div>
						
						<?php if ((count($_productCollection)>0) && !$useSlider): ?>
							<?php if(($this->hasData('loadmore') && $this->getData('loadmore')=='1') && ((!$this->getData('limit')) || (count($_productCollection) == $this->getData('limit')))): ?>
								<a class="btn btn-default btn-loadmore" href="<?php echo $this->getUrl('mpanel/index/loadmore', ['type'=>'deal-products-category', 'category'=>$category->getId(), 'limit'=>$this->getLimit(), 'ratio'=>$this->getRatio(), 'col'=>$col, 'block_id'=>$blockId, 'tabs'=>1, 'p'=>2, 'perrow'=> $perRow]) ?>"><span></span><?php echo __('Load More') ?></a>
							<?php endif ?>
						<?php endif ?>
					</div>
				<?php endforeach ?>
			</div>
		</div>
	<?php else: ?>
		<div role="alert" class="alert alert-warning"><?php echo __('There are no categories matching the selection.') ?></div>
	<?php endif ?>
</div>