<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
 */
?>
<select class="form-control">
	<option value="" selected="selected"><?php echo __('Please choose') ?></option>
	<?php foreach ($filterItems as $filterItem): ?>
		<?php if ($filterItem->getCount() > 0): ?>
			<option value="<?php echo $block->escapeUrl($filterItem->getUrl()) ?>"><?php echo $filterItem->getLabel() ?>
				<?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
					&nbsp;&nbsp;(<?php echo $filterItem->getCount()?>)
				<?php endif; ?>
			</option>
		<?php else:?>
			<option value=""><?php echo $filterItem->getLabel() ?>
				<?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                    (<?php echo $filterItem->getCount()?>)
                <?php endif; ?>
			</option>
		<?php endif; ?>
	<?php endforeach ?>
</select> 
