<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category layered navigation state
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\State
 */
?>
<?php $_filters = $block->getActiveFilters() ?>
<?php if (!empty($_filters)): ?>
    <?php $arFilter = array(); ?>
    <div class="filter-current">
        <div class="block-title">
            <h3 class="block-subtitle filter-current-subtitle" data-count="<?php echo count($_filters); ?>"><?php /* @escapeNotVerified */ echo __('Now Shopping by') ?></h3>
        </div>
        <div class="block-content">
            <ol class="items">
    <?php foreach ($_filters as $_filter): ?>
                    <?php if (!in_array($_filter->getLabel(), $arFilter)): ?>
                        <li class="item h6">
                            <span class="filter-label"><?php echo $block->escapeHtml(__($_filter->getName())); ?></span>
                            <span class="filter-value h6"><?php /* @escapeNotVerified */ echo $block->stripTags($_filter->getLabel()) ?></span>
            <?php
            $clearLinkUrl = $_filter->getClearLinkUrl();
            $currentFilterName = $block->escapeHtml(__($_filter->getName())) . " " . $block->stripTags($_filter->getLabel());
            if ($clearLinkUrl):
                ?>
                                <a class="action previous" href="<?php /* @escapeNotVerified */ echo $_filter->getRemoveUrl() ?>"
                                   title="<?php /* @escapeNotVerified */ echo __('Previous') ?>">
                                    <span><?php /* @escapeNotVerified */ echo __('Previous') ?></span>
                                </a>
                                <a class="action remove"
                                   title="<?php echo $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>"
                                   href="<?php /* @escapeNotVerified */ echo $clearLinkUrl ?>">
                                    <span><?php echo $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></span>
                                </a>
            <?php else: ?>
                                <a class="action remove" href="<?php /* @escapeNotVerified */ echo $_filter->getRemoveUrl() ?>"
                                   title="<?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Remove')) . " " . $currentFilterName; ?>">
                                    <span class="ion-close"></span>
                                </a>
            <?php endif; ?>
                        </li>
                         <?php $arFilter[] =  $_filter->getLabel(); ?>
                        <?php endif; ?>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
<?php endif; ?>
