<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('Upsell Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('Upsell Products');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('Related Products:');
            $items = $block->getItems();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    case 'other':
        break;
}
?>

<?php if ($exist): ?>
    <?php
    $themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
    $themeSettings = $themeHelper->getThemeSettings();
    ?>
    <?php if ($type == 'related'): ?>
        <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
            <div class="block-title"><h3 id="block-<?php echo $class; ?>-heading" role="heading"><?php echo $title ?></h3></div>
            <div class="block-content content">
                <?php if ($canItemsAddToCart): ?>
                    <div class="block-actions">
                        <?php /* @escapeNotVerified */ echo __('Check items to add to the cart or') ?>
                        <button type="button" class="action select btn btn-sm" role="select-all"><span><?php /* @escapeNotVerified */ echo __('select all') ?></span></button>
                    </div>
                <?php endif; ?>
                <div class="products wrapper grid list-products products-<?php echo $type ?> ">
                    <div class="products list items product-items related-carousel">
                        <?php $j=0; foreach ($items as $_item): $j++; ?>
                            <?php $available = ''; ?>
                            <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                <?php if (!$_item->getRequiredOptions()): ?>
                                    <?php $available = 'related-available'; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php if($j % 4 == 1): ?>
                                <div class="slider-item">
                            <?php endif;?>
                            <div class="product-item">
                                <div class="product-item-info <?php /* @escapeNotVerified */ echo $available; ?>">
                                    <div class="product-top">
                                         <?php
                                                $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
                                                $size = $themeHelper->getImageSize($this->getRatio());
                                                $productImage = $_imagehelper->init($_item, $image)->resize($size['width'], $size['height'])->getUrl();
                                                ?>
                                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                                 <img src="<?php echo $productImage; ?>" alt="" class="img-responsive product-image-photo"/>
                                            </a>
                                        <?php if ($showCart): ?>
                                            <div class="product actions product-item-actions">
                                                <?php if ($showCart): ?>
                                                    <div class="actions-primary">
                                                        <?php if ($_item->isSaleable()): ?>
                                                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                                <button class="btn btn-addto" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                    <span class="ion-ios-cart"></span>
                                                                </button>
                                                            <?php else: ?>
                                                                <?php
                                                                $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                                ?>
                                                                <button class="btn btn-addto"
                                                                        data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                        type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                    <span class="ion-ios-cart"></span>
                                                                </button>
                                                            <?php endif; ?>
                                                        <?php else: ?>
                                                            <?php if ($_item->getIsSalable()): ?>
                                                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                            <?php else: ?>
                                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                    <div class="product details product-item-details">
                                        <div class="product name product-item-name"><h4><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                                <?php echo $block->escapeHtml($_item->getName()) ?></a></h4>
                                        </div>

                                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
                                        <div class="meta-box">
                                            <?php if ($templateType): ?>
                                                <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                            <?php endif; ?>
                                            <div class="box-label">
                                                <?php echo $themeHelper->getProductLabel($_item) ?>
                                            </div>                                    
                                        </div>


                                        <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                            <?php if (!$_item->getRequiredOptions()): ?>
                                                <div class="field choice related">
                                                    <input type="checkbox" class="checkbox related" id="related-checkbox<?php /* @escapeNotVerified */ echo $_item->getId() ?>" name="related_products[]" value="<?php /* @escapeNotVerified */ echo $_item->getId() ?>" />
                                                    <label class="label" for="related-checkbox<?php /* @escapeNotVerified */ echo $_item->getId() ?>"><span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span></label>
                                                </div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                            <?php if($j % 4 == 0 || $j == count($items)):?>
                                </div>
                            <?php endif;?>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
                    require([
                        'jquery',
                        'mgs/owlcarousel'
                    ], function ($) {
                        var relatedproduct = $('.related-carousel').owlCarousel({
                            items: 1,
                            autoplay: false,
                            autoplayHoverPause: false,
                            nav: true,
                            navText: ['<span class="ion-arrow-left-c"></span>', '<span class="ion-arrow-right-c"></span>'],
                            dots: false,
                            margin: 30,
                            responsive: {
                                0: {
                                    items: 1,
                                    margin: 0
                                },
                                480: {
                                    items: 1,
                                    margin: 20
                                },
                                768: {
                                    items: 1
                                }
                            }
                        });
                    });
                </script>
    <?php else: ?>
			<?php if ($type == 'upsell'): ?>
            <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
            <?php else: ?>
                <div class="block <?php /* @escapeNotVerified */ echo $class; ?>">
            <?php endif; ?>

                <div class="block-title"><h3><?php echo $title; ?></h3></div>
                <div class="block-content content">
                    <div class="products wrapper grid products-grid products-<?php echo $type ?> <?php echo $themeSettings['catalog']['layout_product'] ?>">
                        <ol class="products list items product-items <?php echo $class; ?>-carousel">
                            <?php foreach ($items as $_item): ?>
                                <li class="product-item item">
                                    <div class="product-item-info" data-container="product-grid">
                                        <div class="product-top">
                                            <?php
                                                $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
                                                $size = $themeHelper->getImageSize($this->getRatio());
                                                $productImage = $_imagehelper->init($_item, $image)->resize($size['width'], $size['height'])->getUrl();
                                                ?>
                                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                                 <img src="<?php echo $productImage; ?>" alt="" class="img-responsive product-image-photo"/>
                                            </a>
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                    <i class="ion-android-favorite-outline"></i>
                                                </a>
                                            <?php endif; ?>
                                            <?php if ($showCompare || $showCart): ?>
												<div class="product-item-inner">
                                                <div class="product actions product-item-actions">
                                                    <?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
                                                    <?php echo $quickViewHelper->aroundQuickViewHtml($_item); ?>
                                                    <?php if ($showCart): ?>
                                                        <div class="actions-primary">
                                                            <?php if ($_item->isSaleable()): ?>
                                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                                    <button class="btn btn-addto" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                        <span class="ion-ios-cart"></span>
                                                                    </button>
                                                                <?php else: ?>
                                                                    <?php
                                                                    $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                                    ?>
                                                                    <button class="btn btn-addto"
                                                                            data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                        <span class="ion-ios-cart"></span>
                                                                    </button>
                                                                <?php endif; ?>
                                                            <?php else: ?>
                                                                <?php if ($_item->getIsSalable()): ?>
                                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                                <?php else: ?>
                                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                                <?php endif; ?>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>

                                                    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                        <?php
                                                        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                        ?>
                                                        <a href="#" class="action tocompare btn btn-addto"
                                                           data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item); ?>'
                                                           data-role="add-to-links"
                                                           title="<?php /* @escapeNotVerified */ echo __('Add to Compare'); ?>">
                                                            <i class="ion-ios-shuffle-strong"></i>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
												</div>
                                            <?php endif; ?>
                                            <?php if ($themeSettings['catalog']['layout_product'] == 'productv1'): ?>
                                                <?php echo $themeHelper->getProductLabel($_item) ?>
                                            <?php endif; ?>
                                        </div>
                                        <div class="product details product-item-details">
                                            <div class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                                    <h4><?php echo $block->escapeHtml($_item->getName()) ?></h4></a>
                                            </div>
                                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>                                            
                                        </div>
                                    </div>
                                </li>
                            <?php endforeach; ?>
                        </ol>
                    </div>
                </div>

            </div>
                <script type="text/javascript">
                    require([
                        'jquery',
                        'mgs/owlcarousel'
                    ], function ($) {
                        var upsellproduct = $('.<?php echo $class?>-carousel').owlCarousel({
                            items: 4,
                            autoplay: false,
                            autoplayHoverPause: false,
                            nav: true,
                            navText: ['<span class="ion-arrow-left-c"></span>', '<span class="ion-arrow-right-c"></span>'],
                            dots: false,
                            margin: 30,
                            responsive: {
                                0: {
                                    items: 1,
                                    margin: 0
                                },
                                480: {
                                    items: 2,
                                    margin: 20
                                },
                                768: {
                                    items: 3
                                },
                                1200:{
                                    items: 4
                                }
                            }
                        });
                    });
                </script>
        <?php endif; ?>
<?php endif; ?>
