<?php $helper = $this->helper('Wanexo\QuickView\Helper\Data'); ?>
<div id="quickview" class="quickview-modal">
	<div class="content-wrap">
    	<div class="quickview-wrapper" style="display:none;">
        	<div class="quick_loading"><?php echo __('Loading...') ?></div>
		</div>
        <div class="quickview-content" style="display:none;"></div>
    </div>
</div>
<script type="text/javascript">
	var url = '';
</script>
<script type="text/x-magento-init">{ "*":{ "Wanexo_QuickView/js/quickview":{ "baseUrl": "<?php echo $helper->getBaseUrl() ?>" } } }
</script>
<script type="text/javascript"> function addMark(id){ var getButton = document.getElementsByClassName('modal-view');for (var i = 0, len = getButton.length; i < len; i++) { getButton[i].classList.remove("active"); } var d = document.getElementById(id);d.className += " active"; }</script>