<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_MultiWishlist
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<form action="<?php echo $block->getUrl('multiwishlist/index/create') ?>" method="post" id="wishlist-form-validation">
    <?php echo $block->getBlockHtml('formkey')?>
    <table class="clean-table linearize-table">
        <tr>
            <td>
                <div class="content-create-wl">
                    <input required id="new_wlname" class="input-text required-entry" type="text"  placeholder="<?php echo __('Enter Wish List Name') ?>"  name="new_wlname"/>
                </div>
                <button class="action primary create-wl" title="<?php echo __('Create Wish List') ?>"  type="submit" ><span><span><?php echo __('Create Wish List') ?></span></span></button>
                <span class="clearfix"></span>
            </td>
        </tr>
    </table>
</form>

<script type="text/javascript">
    require([
        'jquery',
        'mage/mage'
    ], function($){
        var dataForm = $('#wishlist-form-validation');
        dataForm.mage('validation', {});
    });
</script>
