<?php $_productCollection = $this->getRateProductByCategories($this->getCategoryIds()) ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<div class="content-block rate-product-cat-block">
    <?php if ($this->getData('mgs_panel_title')): ?>
        <div class="title-block">
            <h2 class="title"><span><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></span></h2>
            <?php if ($this->getData('mgs_panel_note')): ?>
                <div class="block-note"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_note')) ?></div>
            <?php endif ?>
        </div>
    <?php endif ?>

    <?php if (count($_productCollection) > 0): ?>
        <?php
        $blockId = rand() . time();
        $_helper = $this->helper('Magento\Catalog\Helper\Output');
        $useSlider = $this->getUseSlider();
        $perRow = $this->getPerrow();
        $image = 'category_page_grid';
        $themeSettings = $themeHelper->getThemeSettings();
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        $col = $themeHelper->convertPerRowtoCol($perRow);
        $autoPlay = $this->getAutoplay() ? 'true' : 'false';
        $stopAuto = $this->getStopAuto() ? 'true' : 'false';
        $nav = $this->getNavigation() ? 'true' : 'false';
        $dot = $this->getPagination() ? 'true' : 'false';
        ?>

        <div class="block widget mgs-products rate-products-grid products-grid <?php echo $themeSettings['catalog']['layout_product'] ?>">
            <div class="items product-items <?php echo $themeHelper->convertColClass($col, 'row') ?> <?php if ($useSlider): ?> owl-carousel<?php else: ?> row <?php endif ?>" id="rate-products<?php echo $blockId; ?>">
                <?php $i = 0;
                foreach ($_productCollection as $_product): $i++;
                    ?>
                        <?php $product = $this->getLoadProduct($_product->getId()); ?>
                    <div class="item product product-item<?php if (!$useSlider): ?> <?php echo $themeHelper->convertColClass($col, 'col') ?> <?php echo $themeHelper->getClearClass($perRow, $i) ?> <?php endif ?>">
                            <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        <div class="product-item-info" data-container="product-grid">
                            <?php
                            $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
                            $size = $themeHelper->getImageSize($this->getRatio());
                            $productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();
                            ?>
        <?php // Product Image   ?>
                            <div class="product-top">
                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                    <img src="<?php echo $productImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo"/>

                                </a>
        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$themeSettings['catalog']['wishlist_button']): ?>
                                    <a href="#"
                                       class="action towishlist"
                                       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                       data-action="add-to-wishlist"
                                       role="button">
                                        <i class="ion-android-favorite-outline"></i>
                                    </a>
        <?php endif; ?>
                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions">                                                                                                                           
                                        <?php /* Append Quick View */ ?>
                                        <?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
                                        <?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?>

                                        <?php if ($_product->isSaleable()): ?>
            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                <input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
                                                <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
                                                <button class="action tocart btn-cart btn btn-addto" type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                    <span class="ion-ios-cart icon"></span>
                                                </button>

                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->getIsSalable()): ?>
                                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>

                                        <?php if (!$themeSettings['catalog']['compare_button']): ?>

                                            <?php
                                            $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                            ?>
            <?php if (!$themeSettings['catalog']['compare_button']): ?>
                                                <a href="#"
                                                   class="action tocompare btn btn-addto"
                                                   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                                   role="button">
                                                    <i class="ion-ios-shuffle-strong"></i>
                                                </a>
                                            <?php endif ?>

        <?php endif ?>


                                    </div>
                                </div>
                                <?php if ($themeSettings['catalog']['layout_product'] == 'productv1'): ?>
                                    <?php echo $themeHelper->getProductLabel($_product) ?>
        <?php endif; ?>
                            </div>

                            <div class="product details product-item-details">

                                <div class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                        <h4><?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></h4>
                                    </a>
                                </div>
                                <?php //echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                <?php //echo $block->getProductDetailsHtml($_product);  ?>
        <?php echo $this->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setProduct($_product)->setTemplate('Magento_Swatches::product/listing/renderer.phtml')->toHtml() ?>


                            </div>
                        </div>
                    </div>
    <?php endforeach; ?>
            </div>

    <?php if ($useSlider): ?>
                <script type="text/javascript">
                    require([
                        'jquery',
                        'mgs/owlcarousel'
                    ], function ($) {
                        var owlnewcattab<?php echo $blockId ?> = $('#rate-products<?php echo $blockId ?>').owlCarousel({
                            items: <?php echo $perRow; ?>,
                            autoplay: <?php echo $autoPlay ?>,
                            autoplayHoverPause: <?php echo $stopAuto ?>,
                            nav: <?php echo $nav ?>,
                            navText: ['<span class="ion-ios-arrow-left"></span>', '<span class="ion-ios-arrow-right"></span>'],
                            dots: <?php echo $dot ?>,
                            margin: 30,
                            responsive: {
                                0: {
                                    items: 1,
                                    margin: 0
                                },
                                480: {
                                    items: 2,
                                    margin: 20
                                },
                               768: {
                                                    items:<?php if($perRow >=5): ?> 3 <?php else: ?><?php if($perRow == 3): ?> 2 <?php else: ?> <?php echo $perRow;?><?php endif;?><?php endif;?>
                                                },
                                1200: {
                                    items:<?php echo $perRow; ?>
                                }
                            }
                        });
                    });
                </script>
            <?php else: ?>
                <?php if (count($_productCollection) > 0): ?>
                    <?php if (($this->hasData('loadmore') && $this->getData('loadmore') == '1') && ((!$this->getData('limit')) || (count($_productCollection) == $this->getData('limit')))): ?>
                        <a class="btn btn-default btn-loadmore" href="<?php echo $this->getUrl('mpanel/index/loadmore', ['type' => 'rate-products-category', 'category' => $this->getCategoryIds(), 'limit' => $this->getLimit(), 'ratio' => $this->getRatio(), 'col' => $col, 'block_id' => $blockId, 'tabs' => 0, 'p' => 2, 'perrow' => $perRow]) ?>"><span></span><?php echo __('Load More') ?></a>
                    <?php endif ?>
                <?php endif ?>
    <?php endif ?>
        </div>

    <?php else: ?>
        <div role="alert" class="alert alert-warning"><?php echo __('There are no products matching the selection.') ?></div>
<?php endif ?>
</div>