<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Checkout
 */
?>
<?php
/** @var \Magento\Checkout\Block\Onepage $block */

/** @var \Amasty\Checkout\Helper\Onepage $helper */
$helper = $block->getData('amcheckout_helper');
?>
 
<?php
 /*
 $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');

if ($customerSession->isLoggedIn()) {
    $customer_id = $customerSession->getCustomer()->getId(); 
 $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
 $orderCollection = $objectManager->create('\Magento\Sales\Model\ResourceModel\Order\Collection');
$order_Collection = $orderCollection->addAttributeToFilter('customer_id',$customer_id)
                    ->addFieldToSelect('created_at')
                    ->addAttributeToFilter('subtotal', array('gteq' => 30))
                    ->setPageSize(1)                    
                    ->setOrder('created_at', 'desc'); 
 
                    if(count($order_Collection)>0)
                     {
  
                         foreach($order_Collection as $order)
                        {
                         $LastOrderDate = $order->getCreatedAt();                    
                        }

                      $LastOrder = strtotime($LastOrderDate);
                       $NextTime = date("Y-m-d H:i:s", strtotime('-1  hours'));
                      $CheckTime = strtotime($NextTime);
                      echo 'lastorder date : '.$LastOrderDate.'<br>';
                      echo 'LastOrder : '.$LastOrder.'<br>';
                      echo 'next time : '.$NextTime.'<br>';
                      echo 'check time : '.$CheckTime.'<br>'; 
                    }  
 
} */
?>

<div id="checkout" data-bind="scope:'checkout'" class="checkout-container am-checkout">
    <div class="checkout-header">
        <h1 class="title"><?= $block->escapeHtml($helper->getTitle()) ?></h1>
        <div class="description"><?= $helper->getDescription() ?></div>
    </div>

    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                 alt="<?php /* @escapeNotVerified */ echo __('Loading...'); ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getCheckoutConfig()); ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>");
            return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl();?>');
        });
    </script>
	
    <script>
        require([
            'jquery',
            'domReady!'
        ], function ($) {
            var initCheckout = function(quote, selectBillingAddress, storage, checkoutData, shippingService, registry)
            {
                var defaultAddress = <?= \Zend_Json::encode($helper->getDefaultAddress()) ?>;
                if (defaultAddress) {
                    var mageStorage = $.initNamespaceStorage('mage-cache-storage').localStorage,
                        mageCheckoutData = mageStorage.get('checkout-data');

                    if (!!mageCheckoutData && mageCheckoutData.hasOwnProperty('shippingAddressFromData')) {
                        var shippingAddressFromData = mageCheckoutData.shippingAddressFromData;
                        if (shippingAddressFromData) {
                            Object.keys(shippingAddressFromData).map(function (key) {
                                if (!defaultAddress.hasOwnProperty(key)) {
                                    defaultAddress[key] = shippingAddressFromData[key];
                                }
                            });
                        }

                        if (mageCheckoutData.hasOwnProperty('inputFieldEmailValue')) {
                            var emailValue = mageCheckoutData.inputFieldEmailValue;
                            checkoutData.setInputFieldEmailValue(emailValue);
                            checkoutData.setValidatedEmailValue(emailValue);
                        }
                    }

                    if (defaultAddress.hasOwnProperty('region_id') &&
                        !Number.isInteger(parseInt(defaultAddress['region_id']))) {
                        defaultAddress['region_id'] = undefined;
                    }

                    checkoutData.setShippingAddressFromData(defaultAddress);
                }

                <?php if ($defaultShipping = $helper->getDefaultShippingMethod()) : ?>
                if (!quote.shippingMethod()) {
                    storage.set('amasty-checkout-default-shipping-mehtod', '<?=$defaultShipping?>');
                }

                quote.shippingMethod.extend({ notify: 'always' });

                quote.shippingMethod.subscribe(function(method){
                    if (method === null || method === true) {
                        var ratesData = shippingService.getShippingRates()();
                        var applicableMethod = _.find(ratesData, function (rate) {
                            return rate.carrier_code + '_' + rate.method_code == '<?=$defaultShipping?>';
                        });

                        if (applicableMethod) {
                            registry.get('checkout.steps.shipping-step.shippingAddress', function (shippingComponent) {
                                shippingComponent.selectShippingMethod(applicableMethod);
                            });
                        }
                    }
                });
                <?php endif; ?>

                <?php if ($defaultPayment = $helper->getDefaultPaymentMethod()) : ?>
                if (!quote.paymentMethod() && !checkoutData.getSelectedPaymentMethod()) {
                    checkoutData.setSelectedPaymentMethod('<?=$defaultPayment?>');
                }
                <?php endif ?>

                // fix default "My billing and shipping address are the same" checkbox behaviour
                quote.shippingAddress.subscribe(function (newAddress) {
                    if (!quote.paymentMethod()) {
                        selectBillingAddress(newAddress);
                        return;
                    }

                    var methodComponent = registry.get('checkout.steps.billing-step.payment.payments-list.'+quote.paymentMethod().method+'-form');
                    if (methodComponent && methodComponent.isAddressSameAsShipping()) {
                        selectBillingAddress(newAddress);
                    }
                });
				
            };

            require([
                'Magento_Checkout/js/model/quote',
                'Magento_Checkout/js/action/select-billing-address',
                'Magento_Customer/js/customer-data',
                'Magento_Checkout/js/checkout-data',
                'Magento_Checkout/js/model/shipping-service',
                'uiRegistry',
            ], function(
                quote,
                selectBillingAddress,
                storage,
                checkoutData,
                shippingService,
                registry
            ) {
                initCheckout(quote, selectBillingAddress, storage, checkoutData, shippingService, registry)
            });
        });
    </script>

    <?php if ($helper->isAddressSuggestionEnabled() && ($apiKey = $helper->getGoogleMapsKey())) : ?>
        <script>
            window.amasty_checkout_regions = <?= $helper->getRegionsJson() ?>;

            function amasty_checkout_gmaps_init() {
                require(['Amasty_Checkout/js/autocomplete'], function (autocomplete) {
                    autocomplete.isReady(true);
                });
            }
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=<?= $block->stripTags($apiKey) ?>&libraries=places&callback=amasty_checkout_gmaps_init" async defer></script>
    <?php endif ?>
</div>
<style>
	#checkout-loader{display: none;}
</style>
<script>
    require([
        'jquery'
    ], function ($) {
        'use strict';
        $(window).on('load', function(){
			setTimeout(function() {
				$('#checkout-loader').hide();
			  }, 5000);
            
        });
    });
</script>

