<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerObj = $objectManager->create('Magento\Customer\Model\Customer')
            ->load($block->getCustomer()->getId());
?>
<div class="block block-dashboard-info">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Account Information')) ?></strong></div>
    <div class="block-content">
        <div class="box box-information">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Contact Information')) ?></span>
            </strong>
            <div class="box-content">
                <p>
                    <?= $block->escapeHtml($block->getName()) ?><br>
                    <?= $block->escapeHtml($block->getCustomer()->getEmail()) ?><br>
                </p>
                <?= $block->getChildHtml('customer.account.dashboard.info.extra'); ?>
            </div>
            <div class="box-actions">
                <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>">
                    <span><?= $block->escapeHtml(__('Edit')) ?></span>
                </a>
                <a href="<?= $block->escapeUrl($block->getChangePasswordUrl()) ?>" class="action change-password">
                    <?= $block->escapeHtml(__('Change Password')) ?>
                </a>
            </div>
        </div>
        <?php if ($block->isNewsletterEnabled()): ?>
            <div class="box box-newsletter">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Newsletters')) ?></span>
                </strong>
                <div class="box-content">
                    <p>
                        <?php if ($block->getIsSubscribed()): ?>
                            <?= $block->escapeHtml(__('You are subscribed to "General Subscription".')) ?>
                        <?php else: ?>
                            <?= $block->escapeHtml(__('You aren\'t subscribed to our newsletter.')) ?>
                        <?php endif; ?>
                    </p>
                </div>
                <div class="box-actions">
                    <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('newsletter')) ?>"><span><?= $block->escapeHtml(__('Edit')) ?></span></a>
                </div>
            </div>
        <?php endif; ?>
		<?php if ($customerObj->getCustomNetTerms() || $customerObj->getPOLimit() || $customerObj->getCustomPOCredit()): ?>
            <div class="box box-newsletter box-po-terms">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('PO Terms')) ?></span>
                </strong>
                <div class="box-content">
                    <p>
                        <?php if ($customerObj->getCustomNetTerms()): ?>
                           <span><strong><?php echo $block->escapeHtml(__('PO Terms: '))?></strong><?php echo $customerObj->getCustomNetTerms()?></span> 
                        <?php endif; ?>
                    </p>
					<p>
                        <?php if ($customerObj->getCustomPoLimit()): ?>
                           <span><strong><?php echo $block->escapeHtml(__('PO Limit: '))?></strong><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($customerObj->getCustomPoLimit(),true,false);?></span> 
                        <?php endif; ?>
                    </p>
					<p>
                        <?php if ($customerObj->getCustomPoCredit()): ?>
                           <span><strong><?php echo $block->escapeHtml(__('PO Credit(DUE): '))?></strong><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($customerObj->getCustomPoCredit(),true,false);?></span> 
                        <?php endif; ?>
                    </p>
                </div>
                
            </div>
        <?php endif; ?>
    </div>
</div>
