<?php $helper = $this->helper('MGS\Blog\Helper\Data'); ?>
<?php if ($block->getConfig('general_settings/enabled')): ?>
    <?php if ($block->getConfig('sidebar_settings/enabled')): ?>
        <?php if ($block->getConfig('sidebar_settings/show_categories')): ?>
            <?php
            $categories = $block->getCategories();
            ?>
            <?php if (count($categories)): ?>
                <div class="block block-blog-categories">
                    <div class="block-title">
                        <h3 id="block-blog-categories-heading"><?php echo __('Categories') ?></h3>
                    </div>
                    <div class="block-content">
                        <ul class="category-list">
                            <?php foreach ($categories as $category): ?>
                                <li class="item">
                                    <div class="category-info">
                                        <a title="<?php echo $category->getTitle(); ?>"
                                           href="<?php echo $category->getCategoryUrl(); ?>">
                                            <span class="title"><?php echo $category->getTitle(); ?></span>
                                            <span class="count"><?php echo $this->getCountCate($category->getId()); ?></span>
                                        </a>
                                    </div>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($block->getConfig('sidebar_settings/show_recent_posts')): ?>
            <?php
            $collection = $block->getCollection();
            $showThumbnail = $this->getConfig('sidebar_settings/show_thumbnail');
            if ($this->getConfig('sidebar_settings/thumbnail_width') != '') {
                $width = $this->getConfig('sidebar_settings/thumbnail_width');
            } else {
                $width = 80;
            }
            if ($this->getConfig('sidebar_settings/thumbnail_height') != '') {
                $height = $this->getConfig('sidebar_settings/thumbnail_height');
            } else {
                $height = 20;
            }
            ?>
            <?php if ($collection->count()): ?>
                <div class="block block-blog-posts">
                    <div class="block-title">
                        <h3 id="block-blog-posts-heading"><?php echo __('Popular Posts') ?></h3>
                    </div>
                    <div class="block-content">
                        <ul class="post-list">
                            <?php foreach ($collection as $post): ?>
                                <li class="item">
                                    <div class="post-img col-md-4 col-sm-12 col-xs-4">
                                        <div class="row">
                                            <?php if ($showThumbnail): ?>

                                                <?php if ($post->getThumbType() == "video"): ?>

                                                    <?php if ($helper->getThumbnailImgVideoPost($post) != ""): ?>
                                                        <a title="<?php echo $post->getTitle(); ?>" href="<?php echo $post->getPostUrlWithNoCategory(); ?>">
                                                            <div class="video image" data-toggle="modal" data-target="#postModal-sidebar--<?php echo $post->getId() ?>">
                                                                <img class="img-responsive" src="<?php echo $helper->getThumbnailImgVideoPost($post); ?>" />
                                                            </div>
                                                        </a>
                                                    <?php endif ?>

                                                <?php else: ?>
                                                    <div class="image"><?php echo $helper->getThumbnailPost($post); ?></div>
                                                <?php endif ?>

                                            <?php endif ?>
                                        </div>
                                    </div>
                                    <div class="post-name col-md-8 col-sm-12 col-xs-8">
                                        <div class="row">
                                            <em class="h5 date_time"><?php echo __('%1', $block->formatDate($post->getCreatedAt(), \IntlDateFormatter::LONG, false)); ?></em>
                                            <a title="<?php echo $post->getTitle(); ?>"
                                               href="<?php echo $post->getPostUrlWithNoCategory(); ?>">
                                                <p class="h5"><?php echo $post->getTitle(); ?></p>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('organie_blog_ads')->toHtml()): ?>
            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('organie_blog_ads')->toHtml(); ?>
        <?php endif ?>
        <?php if ($block->getConfig('sidebar_settings/show_tags')): ?>
            <?php $tags = $block->getTags(); ?>
            <?php if (count($tags)): ?>
                <div class="block block-blog-tags">
                    <div class="block-title">
                        <h3 id="block-blog-tags-heading"><?php echo __('Search by Tags') ?></h3>
                    </div>
                    <div class="block-content">
                        <?php
                        $total = 0;
                        foreach ($tags as $tag => $count) {
                            $total += $count;
                        }
                        ?>
                        <?php
                        foreach ($tags as $tag => $count):
                            $percent = floor(($count / $total) * 100);
                            if ($percent < 20):
                                $class = 'smallest';
                            elseif ($percent >= 20 and $percent < 40):
                                $class = 'small';
                            elseif ($percent >= 40 and $percent < 60):
                                $class = 'medium';
                            elseif ($percent >= 60 and $percent < 80):
                                $class = 'large';
                            else:
                                $class = 'largest';
                            endif;
                            ?>
                            <span class="<?php echo $class; ?>">
                                <a class="btn-tag" title="<?php echo $tag; ?>" href="<?php echo $helper->getTagUrl($tag); ?>"><?php echo $tag; ?></a>
                            </span>
                        <?php endforeach; ?>
                    </div>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
