<?php

/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$themeSettings = $themeHelper->getThemeSettings();
$colClass = $themeHelper->getColClass();
$arrColClass = explode(' ', $colClass);
$pageType = 'catalog';
if ($this->hasData('page_type')) {
    $pageType = $this->getData('page_type');
}
$_akeansHelper = $this->helper('Akeans\ShowPriceAfterLogin\Helper\Data');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <div class="top-toolbar">
        <?php echo $block->getToolbarHtml() ?>
    </div>

    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?> <?php echo $themeSettings['catalog']['layout_product'] ?>" id="product-wrapper">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items row <?php echo 'row-' . $arrColClass[0] ?>">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php
            $i = 0;
            foreach ($_productCollection as $_product): $i++;
            // check true or false to show hide price or add to cart button
						$akeans_check = $_akeansHelper->checkVisible($_product);
                ?>        
                <?php
                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                ?>
                <?php if ($block->getMode() == 'grid'): ?>
                    <li class="item product product-item <?php echo $colClass ?> <?php echo $themeHelper->getClearClass('', $i) ?>">
			
                        <div class="product-item-info" data-container="product-grid">
                           <?php
                            $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
                            $size = $themeHelper->getImageSize();
                            $productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();
                            //$block->getImage($_product, $image);
                            ?>
                            <?php // Product Image    ?>
                            <div class="product-top">
                                <a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                    <img src="<?php echo $productImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo"/>
                                </a>
                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$themeSettings['catalog']['wishlist_button']): ?>
                                    <a href="#"
                                       class="action towishlist"
                                       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                       data-action="add-to-wishlist"
                                       role="button">
                                        <i class="ion-android-favorite-outline"></i>
                                    </a>
                                <?php endif; ?>
                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions" id="<?php echo $_product->getId();?>">
                                        <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                        <?php /* Append Quick View */ ?>
                                        <?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
                                        <?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?>

                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                <?php echo $block->getBlockHtml('formkey') ?>
                                                <?php if(!$_akeansHelper->isCustomerlogin() && $_akeansHelper->isEnableShowPriceAfterLogin() && $akeans_check): 
											$redirect_url = $_akeansHelper->getRedirectUrl();
											if($redirect_url){
											?>
                                                <a  class="action tocart primary" href="<?php echo $block->getUrl($redirect_url); ?>">
                                                    <?php  echo $_akeansHelper->getButtonTitle();?>
                                                </a>
											<?php }else{?>
												<a  class="action tocart primary" href="<?php echo $block->getUrl('customer/account/login'); ?>">
                                                    <?php  echo $_akeansHelper->getButtonTitle();?>
                                                </a>
											<?php }?>
											 <?php elseif($_akeansHelper->isCustomerlogin() && $_akeansHelper->isEnableShowPriceAfterLogin() && !$akeans_check):?>	
											<?php $redirect_url = $_akeansHelper->getRedirectUrl();
											if($redirect_url){
											?>
                                                <a  class="action tocart primary" href="<?php echo $block->getUrl($redirect_url); ?>">
                                                    <?php  echo $_akeansHelper->getCallPriceLabel();?>
                                                </a>
											<?php }else{?>
												<a  class="action tocart primary" href="<?php echo $block->getUrl('customer/account/login'); ?>">
                                                    <?php  echo $_akeansHelper->getCallPriceLabel();?>
                                                </a>
											<?php }?>
											<?php else:?>
                                            <button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                        class="btn btn-primary btn-cart btn-addto action tocart salebtn<?php echo $_product->getId();?>" <?php if($_product->getData('isspecial') == 1){?>
                                                        style="display:none;" <?php }?>>
                                                    <span class="ion-ios-cart"></span>
                                                </button>
                                            <?php if($_product->getData('isspecial') == 1){?>
                                            <span id="cart-msg-popup<?php echo $_product->getId();?>" class="btn btn-primary btn-cart btn-addto action tocart cart-msg-popup<?php echo $_product->getId();?>">
                                            <span class="ion-ios-cart"></span>    
                                            </span>
                                            <div id="popup-modal<?php echo $_product->getId();?>" style="display:none;">
                                                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('add-cart-popup')->toHtml(); ?>
                                                <div class="sales-pop-btns">
                                                <span class="sal-btn-cart" pid="<?php echo $_product->getId();?>"><?php echo $block->escapeHtml(__('Yes')); ?></span>
                                                
                                                <button class="action-close-1" data-role="closeBtn" type="button">
                                                    <span>No</span>
                                                </button>   
                                                    
                                                </div>
                                            </div>
                                            <script>
                                                require(
                                                    [
                                                        'jquery',
                                                        'Magento_Ui/js/modal/modal'
                                                    ],
                                                    function(
                                                        $,
                                                        modal
                                                    ) {
                                                        var options = {
                                                            type: 'popup',
                                                            responsive: true,
                                                            innerScroll: true,
                                                            modalClass: 'cart-sale-popup',
                                                            //title: 'popup modal title',
                                                            //buttons: [{
                                                             //   text: $.mage.__('Continue'),
                                                              //  class: '',
                                                             //   click: function () {
                                                             //       this.closeModal();
                                                              //  }
                                                           // }]
                                                        };

                                                        var popup = modal(options, $('#popup-modal<?php echo $_product->getId();?>'));
                                                        $(".cart-msg-popup<?php echo $_product->getId();?>").on('click',function(){ 
                                                            $("#popup-modal<?php echo $_product->getId();?>").modal("openModal");
                                                        });
                                                        $('.sal-btn-cart').on('click', function() {
                                                            //alert($(this).attr('pid'));
                                                            if($(this).attr('pid') == '<?php echo $_product->getId();?>'){
                                                                $("#popup-modal<?php echo $_product->getId();?>").modal("closeModal");
                                                                $('button.btn-cart.salebtn<?php echo $_product->getId();?>')[0].click();
                                                            }
                                                            
                                                        });
                                                    }
                                                );
                                                   
                                            </script>    
                                            <?php }?>
                                            <?php if (!$themeSettings['catalog']['compare_button']): ?>
                                            <?php
                                            $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                            ?>
                                            <?php if (!$themeSettings['catalog']['compare_button']): ?>
                                                <a href="#"
                                                   class="action tocompare btn btn-addto"
                                                   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                                   role="button">
                                                    <i class="ion-ios-shuffle-strong"></i>
                                                </a>
                                            <?php endif ?>

                                        <?php endif ?>    
											<?php endif; ?>
                                                
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->getIsSalable()): ?>
                                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>

                                        
                                    </div>
                                  </div>
                                </div>
                                <?php if ($themeSettings['catalog']['layout_product'] == 'productv1'): ?>
                                    <?php echo $themeHelper->getProductLabel($_product) ?>
                                <?php endif; ?>
                            </div>

                            <div class="product details product-item-details">
                                <div class="product name product-item-name">
                                    <a class="product-item-link" href="<?php echo $_product->getProductUrl() ?>">
                                        <h4><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></h4>
                                    </a>
                                </div>
                                <?php //echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                
                                <?php 
						
						
						
						if(!$_akeansHelper->isCustomerlogin() && $_akeansHelper->isEnableShowPriceAfterLogin() && $akeans_check): 
						
						?>
						<?php elseif($_akeansHelper->isCustomerlogin() && $_akeansHelper->isEnableShowPriceAfterLogin() && !$akeans_check):
						
						?>
						<?php else:?>
                        <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
						<?php endif?>
                                
                                <?php echo $block->getProductDetailsHtml($_product); ?>
                            </div>
                        </div>
                    </li>
                <?php else: ?>
                    <?php //PRODUCT LIST  ?>
                    <li class="item product product-item col-md-12 col-sm-12 col-xs-12">
                        <div class="product-item-info row" data-container="product-grid">
                            <?php
                            $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
                            $size = $themeHelper->getImageSize();
                            $productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();
                            ?>
                            <?php // Product Image   ?>
                            <div class="product-top col-md-4 col-sm-5 col-xs-12">
                                <a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                    <img src="<?php echo $productImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo"/>

                                </a>
                            </div>

                            <div class="product details product-item-details col-md-8 col-sm-7 col-xs-12">
                                <div class="top-details row">  
                                    <div class="col-md-9 col-sm-8 col-xs-12">
                                        <div class="label-box">
                                            <?php echo $themeHelper->getProductLabel($_product) ?>
                                        </div>                                        
                                        <div class="product name product-item-name">
                                            <a class="product-item-link" href="<?php echo $_product->getProductUrl() ?>">
                                                <h4><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></h4>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-md-3 col-sm-4 col-xs-12">
                                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
                                    </div>
                                </div>
                                <?php 
                                if(!$_akeansHelper->isCustomerlogin() && $_akeansHelper->isEnableShowPriceAfterLogin() && $akeans_check): 
                                ?>
                                <?php elseif($_akeansHelper->isCustomerlogin() && $_akeansHelper->isEnableShowPriceAfterLogin() && !$akeans_check):
                                ?>
                                <?php else:?>
                                <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                                <?php endif?>                                
                                <?php echo $block->getProductDetailsHtml($_product); ?>
                                <?php if ($showDescription): ?>
                                    <div class="product description product-item-description">
                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>

                                    </div>
                                <?php endif; ?>
                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions">
                                        <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                <?php echo $block->getBlockHtml('formkey') ?>
                                                <?php if(!$_akeansHelper->isCustomerlogin() && $_akeansHelper->isEnableShowPriceAfterLogin() &&$akeans_check): 
											$redirect_url = $_akeansHelper->getRedirectUrl();
											if($redirect_url){
											?>
                                                <a  class="action tocart primary" href="<?php echo $block->getUrl($redirect_url); ?>">
                                                    <?php  echo $_akeansHelper->getButtonTitle();?>
                                                </a>
											<?php }else{?>
												<a  class="action tocart primary" href="<?php echo $block->getUrl('customer/account/login'); ?>">
                                                    <?php  echo $_akeansHelper->getButtonTitle();?>
                                                </a>
											<?php }?>
											 <?php elseif($_akeansHelper->isCustomerlogin() && $_akeansHelper->isEnableShowPriceAfterLogin() && !$akeans_check):?>	
											<?php $redirect_url = $_akeansHelper->getRedirectUrl();
											if($redirect_url){
											?>
                                                <a  class="action tocart primary" href="<?php echo $block->getUrl($redirect_url); ?>">
                                                    <?php  echo $_akeansHelper->getCallPriceLabel();?>
                                                </a>
											<?php }else{?>
												<a  class="action tocart primary" href="<?php echo $block->getUrl('customer/account/login'); ?>">
                                                    <?php  echo $_akeansHelper->getCallPriceLabel();?>
                                                </a>
											<?php }?>
											<?php else:?>
                                                <button type="submit"
                                                        title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                        class="btn btn-primary btn-cart action tocart salebtn<?php echo $_product->getId();?>" <?php if($_product->getData('isspecial') == 1){?>
                                                        style="display:none;" <?php }?>>
                                                    <div class="text"><?php echo __('Add to cart') ?></div>
                                                </button>
                                                
                                                <?php if($_product->getData('isspecial') == 1){?>
                                                <span id="cart-msg-popup<?php echo $_product->getId();?>" class="btn btn-primary btn-cart action tocart cart-msg-popup<?php echo $_product->getId();?>">
                                                <span class="text"><?php echo __('Add to cart') ?></span>   
                                                </span>
                                                <div id="popup-modal<?php echo $_product->getId();?>" style="display:none;">
                                                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('add-cart-popup')->toHtml(); ?>
                                                <div class="sales-pop-btns">
                                                <span class="sal-btn-cart" pid="<?php echo $_product->getId();?>"><?php echo $block->escapeHtml(__('Yes')); ?></span>
                                                
                                                <button class="action-close-1" data-role="closeBtn" type="button">
                                                    <span>No</span>
                                                </button>   
                                                    
                                                </div>
                                            </div>
                                            <script>
                                                require(
                                                    [
                                                        'jquery',
                                                        'Magento_Ui/js/modal/modal'
                                                    ],
                                                    function(
                                                        $,
                                                        modal
                                                    ) {
                                                        var options = {
                                                            type: 'popup',
                                                            responsive: true,
                                                            innerScroll: true,
                                                            modalClass: 'cart-sale-popup',
                                                            //title: 'popup modal title',
                                                            //buttons: [{
                                                             //   text: $.mage.__('Continue'),
                                                              //  class: '',
                                                             //   click: function () {
                                                             //       this.closeModal();
                                                              //  }
                                                           // }]
                                                        };

                                                        var popup = modal(options, $('#popup-modal<?php echo $_product->getId();?>'));
                                                        $(".cart-msg-popup<?php echo $_product->getId();?>").on('click',function(){ 
                                                            $("#popup-modal<?php echo $_product->getId();?>").modal("openModal");
                                                        });
                                                        $('.sal-btn-cart').on('click', function() {
                                                            //alert($(this).attr('pid'));
                                                            if($(this).attr('pid') == '<?php echo $_product->getId();?>'){
                                                                $("#popup-modal<?php echo $_product->getId();?>").modal("closeModal");
                                                                $('button.btn-cart.salebtn<?php echo $_product->getId();?>')[0].click();
                                                            }
                                                            
                                                        });
                                                    }
                                                );
                                                   
                                            </script> 
                                                <?php } ?>
                                            <?php endif; ?>    
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->getIsSalable()): ?>
                                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>

                                        <?php if (!$themeSettings['catalog']['wishlist_button'] || !$themeSettings['catalog']['compare_button']): ?>

                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$themeSettings['catalog']['wishlist_button']): ?>
                                                <a href="#"
                                                   class="action towishlist btn btn-default btn-addto"
                                                   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                                   data-action="add-to-wishlist"
                                                   role="button">
                                                    <i class="ion-heart"></i>
                                                </a>
                                            <?php endif; ?>

                                        <?php endif ?>
                                    </div>
                                    </div>    
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endif; ?>

            <?php endforeach; ?>
        </ol>
    </div>
    <div class="bottom-toolbar">
        <?php echo $block->getToolbarHtml() ?>
    </div>
    
<?php endif; ?>


    
