<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$themeSettings = $themeHelper->getThemeSettings();
$_akeansHelper = $this->helper('Akeans\ShowPriceAfterLogin\Helper\Data');
$akeans_check = $_akeansHelper->checkVisible($_product);
?>
<?php if ($_product->isSaleable()): ?>

    <div class="box-tocart">
        <div class="fieldset">
            
            <?php if(!$_akeansHelper->isCustomerlogin() && $_akeansHelper->isEnableShowPriceAfterLogin() && $akeans_check): 
            $redirect_url = $_akeansHelper->getRedirectUrl();
            if($redirect_url){
            ?>
                <a  class="action tocart primary" href="<?php echo $block->getUrl($redirect_url); ?>">
                    <?php  echo $_akeansHelper->getButtonTitle();?>
                </a>
            <?php }else{?>
                <a  class="action tocart primary" href="<?php echo $block->getUrl('customer/account/login'); ?>">
                    <?php  echo $_akeansHelper->getButtonTitle();?>
                </a>
            <?php }?>
            <?php elseif($_akeansHelper->isCustomerlogin() && $_akeansHelper->isEnableShowPriceAfterLogin() && !$akeans_check):?>	
            <?php $redirect_url = $_akeansHelper->getRedirectUrl();
            if($redirect_url){
            ?>
                <a  class="action tocart primary" href="<?php echo $block->getUrl($redirect_url); ?>">
                    <?php  echo $_akeansHelper->getCallPriceLabel();?>
                </a>
            <?php }else{?>
                <a  class="action tocart primary" href="<?php echo $block->getUrl('customer/account/login'); ?>">
                    <?php  echo $_akeansHelper->getCallPriceLabel();?>
                </a>
            <?php }?>
            <?php else:?>
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">            
                    <div class="control">
                        <span class="edit-qty minus" onclick="minusQty('qty')"><i class="ion-ios-minus-outline"></i></span>
                        <input type="number"
                               name="qty"
                               id="qty"
                               maxlength="12"
                               value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                               title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                               />
                        <span class="edit-qty plus" onclick="plusQty('qty')"><i class="ion-ios-plus-outline"></i></span>
                    </div>
                   
                </div>
            <?php endif; ?>
            
            <div class="actions">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>" id="product-addtocart-button"
                        class="action primary tocart btn btn-primary salebtn<?php echo $_product->getId();?>" <?php if($_product->getData('isspecial') == 1){?> style="display:none;" <?php }?>>
                    <span class="text"><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>
                <?php if($_product->getData('isspecial') == 1){?>
                                            <span id="cart-msg-popup<?php echo $_product->getId();?>" class="action primary tocart btn btn-primary cart-msg-popup<?php echo $_product->getId();?>">
                                            <span class="text"><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>   
                                            </span>
                                            <div id="popup-modal<?php echo $_product->getId();?>" style="display:none;">
                                                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('add-cart-popup')->toHtml(); ?>
                                                <div class="sales-pop-btns">
                                                <span class="sal-btn-cart" pid="<?php echo $_product->getId();?>"><?php echo $block->escapeHtml(__('Yes')); ?></span>
                                                
                                                <button class="action-close-1" data-role="closeBtn" type="button">
                                                    <span>No</span>
                                                </button>   
                                                    
                                                </div>
                                            </div>
                                            <script>
                                                require(
                                                    [
                                                        'jquery',
                                                        'Magento_Ui/js/modal/modal'
                                                    ],
                                                    function(
                                                        $,
                                                        modal
                                                    ) {
                                                        var options = {
                                                            type: 'popup',
                                                            responsive: true,
                                                            innerScroll: true,
                                                            modalClass: 'cart-sale-popup',
                                                            //title: 'popup modal title',
                                                            //buttons: [{
                                                             //   text: $.mage.__('Continue'),
                                                              //  class: '',
                                                             //   click: function () {
                                                             //       this.closeModal();
                                                              //  }
                                                           // }]
                                                        };

                                                        var popup = modal(options, $('#popup-modal<?php echo $_product->getId();?>'));
                                                        $(".cart-msg-popup<?php echo $_product->getId();?>").on('click',function(){ 
                                                            $("#popup-modal<?php echo $_product->getId();?>").modal("openModal");
                                                        });
                                                        $('.sal-btn-cart').on('click', function() {
                                                            //alert($(this).attr('pid'));
                                                            if($(this).attr('pid') == '<?php echo $_product->getId();?>'){
                                                                $("#popup-modal<?php echo $_product->getId();?>").modal("closeModal");
                                                                $('button.salebtn<?php echo $_product->getId();?>')[0].click();
                                                            }
                                                            
                                                        });
                                                    }
                                                );
                                                   
                                            </script> 
                                            <?php }?>   
                <?php echo $block->getChildHtml('', true) ?>
            </div><?php endif; ?> 
        </div>
    </div>
    <script type="text/javascript">
        function plusQty(qtyInput){
                require([
                'jquery'
                ], function(jQuery){
                        (function($) {
                                if($('#'+qtyInput).attr('disabled')!='disabled'){
                                        qty = $('#'+qtyInput).attr('value');
                                        qty = parseInt(qty);
                                        qty++;
                                        $('#'+qtyInput).val(qty);
                                }
                        })(jQuery);
                });

        }
        function minusQty(qtyInput){
                require([
                'jquery'
                ], function(jQuery){
                        (function($) {
                                if($('#'+qtyInput).attr('disabled')!='disabled'){
                                        qty = $('#'+qtyInput).attr('value');
                                        qty = parseInt(qty);

                                        if(qty>1){
                                                qty--;
                                                $('#'+qtyInput).val(qty);
                                        }
                                }
                        })(jQuery);
                });
        }
        </script>
<?php endif; ?>
<?php if ($themeSettings['product_details']['wishlist'] || $themeSettings['product_details']['compare'] || $block->canEmailToFriend()): ?>
    <div class="product-addto">       
        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $themeSettings['product_details']['wishlist'] != NULL): ?>
            <a href="#"
               class="action towishlist btn btn-addto"
               title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
               aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
               data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
               data-action="add-to-wishlist"
               role="button">
                <i class="ion-android-favorite-outline"></i>
            </a>
        <?php endif; ?>
        <?php
        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
        ?>
        <?php if ($themeSettings['product_details']['compare'] != NULL && $compareHelper != NULL): ?>
            <a href="#"
               class="action tocompare btn btn-addto"
               title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
               aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
               data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
               role="button">
                <i class="ion-ios-shuffle-strong"></i>
            </a>
        <?php endif ?>
        <?php if ($block->canEmailToFriend()): ?>
            <a href="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>"
               class="action mailto friend"><i class="fa fa-mail"></i></a>
            <?php endif; ?>
    </div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
        {
        "#product_addtocart_form": {
        "Magento_Catalog/product/view/validation": {
        "radioCheckboxClosest": ".nested"
        }
        }
        }
    </script>
<?php else : ?>
    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Magento_Catalog/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';

            $('#product_addtocart_form').mage('validation', {
                radioCheckboxClosest: '.nested',
                submitHandler: function (form) {
                    var widget = $(form).catalogAddToCart({
                        bindSubmit: false
                    });

                    widget.catalogAddToCart('submitForm', $(form));

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>
