<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_product = $block->getProduct(); ?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */ ?>
<?php echo $block->getReviewsSummaryHtml($block->getProduct(), false, true)?>
<?php if ($block->displayProductStockStatus()): ?>
  <?php if ($_product->isAvailable()): ?>
    <div class="stock available" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
        <span><i class="ion-ios-checkmark"></i><?php /* @escapeNotVerified */ echo __('In stock') ?></span>
    </div>
  <?php endif; ?>
<?php endif; ?>